# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from BaseClasses import ItemClassification
from .types.Items import ItemData, SingleItemData

num_types = 676

single_items_data: list[SingleItemData] = [
    SingleItemData(item_id=0, name='Golden Triangle', classification=ItemClassification.filler),
    SingleItemData(item_id=1, name='Sandwich', classification=ItemClassification.filler),
    SingleItemData(item_id=2, name='Green Leaf Tea', classification=ItemClassification.filler),
    SingleItemData(item_id=3, name='Sweet Berry Tea', classification=ItemClassification.filler),
    SingleItemData(item_id=6, name='Masterball', classification=ItemClassification.filler),
    SingleItemData(item_id=7, name='Blue Shell', classification=ItemClassification.filler),
    SingleItemData(item_id=8, name='Hardwood Stave', classification=ItemClassification.useful),
    SingleItemData(item_id=9, name="Miner's Helmet", classification=ItemClassification.useful),
    SingleItemData(item_id=10, name='Lunatic Paws', classification=ItemClassification.useful),
    SingleItemData(item_id=11, name='Timeworn Belt', classification=ItemClassification.useful),
    SingleItemData(item_id=13, name='Humming Razor', classification=ItemClassification.useful),
    SingleItemData(item_id=15, name='Scarecrown', classification=ItemClassification.useful),
    SingleItemData(item_id=16, name='Holiday Boots', classification=ItemClassification.filler),
    SingleItemData(item_id=18, name='Dungeon Heart', classification=ItemClassification.filler),
    SingleItemData(item_id=23, name='Rookiehat', classification=ItemClassification.useful),
    SingleItemData(item_id=24, name='Rookieblade', classification=ItemClassification.useful),
    SingleItemData(item_id=25, name='Rookieboots', classification=ItemClassification.useful),
    SingleItemData(item_id=26, name='Rookiebelt', classification=ItemClassification.useful),
    SingleItemData(item_id=27, name='Hi-Sandwich', classification=ItemClassification.filler),
    SingleItemData(item_id=28, name='Chef Sandwich', classification=ItemClassification.filler),
    SingleItemData(item_id=29, name='Bronze Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=30, name='Bronze Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=31, name='Bronze Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=32, name='Bronze Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=33, name='Grasswalkers', classification=ItemClassification.useful),
    SingleItemData(item_id=34, name="Explorer's Cap", classification=ItemClassification.useful),
    SingleItemData(item_id=35, name="Edge o' All", classification=ItemClassification.useful),
    SingleItemData(item_id=36, name='Second Hide', classification=ItemClassification.useful),
    SingleItemData(item_id=37, name='Civilian Trigger', classification=ItemClassification.useful),
    SingleItemData(item_id=38, name='Winterclaw', classification=ItemClassification.useful),
    SingleItemData(item_id=39, name="Winner's Pride", classification=ItemClassification.useful),
    SingleItemData(item_id=40, name='Mega-Sandwich', classification=ItemClassification.filler),
    SingleItemData(item_id=41, name='Bovine Armor', classification=ItemClassification.useful),
    SingleItemData(item_id=42, name='Swiftspike', classification=ItemClassification.useful),
    SingleItemData(item_id=43, name='Weird Skates', classification=ItemClassification.useful),
    SingleItemData(item_id=44, name='Rusty Anchors', classification=ItemClassification.useful),
    SingleItemData(item_id=45, name='Fleety Sandals', classification=ItemClassification.useful),
    SingleItemData(item_id=46, name='Feline Paws', classification=ItemClassification.useful),
    SingleItemData(item_id=47, name='Leaf Cape', classification=ItemClassification.useful),
    SingleItemData(item_id=48, name='Assault Vest', classification=ItemClassification.useful),
    SingleItemData(item_id=49, name="Recruit's Scope", classification=ItemClassification.useful),
    SingleItemData(item_id=50, name='Shady Monocle', classification=ItemClassification.useful),
    SingleItemData(item_id=51, name='Key Piece', classification=ItemClassification.progression),
    SingleItemData(item_id=53, name="Winner's Proof", classification=ItemClassification.useful),
    SingleItemData(item_id=54, name='Dented Crown', classification=ItemClassification.useful),
    SingleItemData(item_id=55, name="Student's Bandana", classification=ItemClassification.useful),
    SingleItemData(item_id=56, name="Mugger's Blade", classification=ItemClassification.useful),
    SingleItemData(item_id=57, name='Daikon', classification=ItemClassification.useful),
    SingleItemData(item_id=58, name='Hydra Fang', classification=ItemClassification.useful),
    SingleItemData(item_id=59, name='Scrappy Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=60, name='Bull Stompers', classification=ItemClassification.useful),
    SingleItemData(item_id=61, name='Perfect Karrot', classification=ItemClassification.filler),
    SingleItemData(item_id=62, name='Precursor Shard', classification=ItemClassification.progression),
    SingleItemData(item_id=63, name='Cross Sandwich', classification=ItemClassification.filler),
    SingleItemData(item_id=64, name='Spicy Bun', classification=ItemClassification.filler),
    SingleItemData(item_id=65, name='Flaming Bun', classification=ItemClassification.filler),
    SingleItemData(item_id=66, name='Blazing Bun', classification=ItemClassification.filler),
    SingleItemData(item_id=67, name='Veggie Sticks', classification=ItemClassification.filler),
    SingleItemData(item_id=68, name='Veggie Wraps', classification=ItemClassification.filler),
    SingleItemData(item_id=69, name='Veggie Burger', classification=ItemClassification.filler),
    SingleItemData(item_id=70, name='Fruit Drink', classification=ItemClassification.filler),
    SingleItemData(item_id=71, name='Fruit Salad', classification=ItemClassification.filler),
    SingleItemData(item_id=72, name='Fruit Pie', classification=ItemClassification.filler),
    SingleItemData(item_id=73, name='Rice Cracker', classification=ItemClassification.filler),
    SingleItemData(item_id=74, name='Tofu Cracker', classification=ItemClassification.filler),
    SingleItemData(item_id=75, name='Cheese Cracker', classification=ItemClassification.filler),
    SingleItemData(item_id=76, name='Salty Ice Cream', classification=ItemClassification.filler),
    SingleItemData(item_id=77, name='Chili Con Carne', classification=ItemClassification.filler),
    SingleItemData(item_id=78, name='Ginger Tom. Salad', classification=ItemClassification.filler),
    SingleItemData(item_id=79, name='Pepper Night Tea', classification=ItemClassification.filler),
    SingleItemData(item_id=80, name='Headphone Scraps', classification=ItemClassification.filler),
    SingleItemData(item_id=81, name='Metal Needles', classification=ItemClassification.filler),
    SingleItemData(item_id=82, name='Bovine Skin', classification=ItemClassification.filler),
    SingleItemData(item_id=83, name='Edgy Headphones', classification=ItemClassification.useful),
    SingleItemData(item_id=84, name='Climbing Pick', classification=ItemClassification.useful),
    SingleItemData(item_id=85, name='Boom Walkers', classification=ItemClassification.useful),
    SingleItemData(item_id=86, name='Golden Ring', classification=ItemClassification.filler),
    SingleItemData(item_id=87, name='Chili Dog', classification=ItemClassification.filler),
    SingleItemData(item_id=88, name='Raw Meat', classification=ItemClassification.filler),
    SingleItemData(item_id=89, name='Core Drill', classification=ItemClassification.useful),
    SingleItemData(item_id=90, name='Giga Spiral Drill', classification=ItemClassification.useful),
    SingleItemData(item_id=91, name='Autumn Leaves', classification=ItemClassification.filler),
    SingleItemData(item_id=92, name='Season Apples', classification=ItemClassification.filler),
    SingleItemData(item_id=93, name='Gold Beetle', classification=ItemClassification.filler),
    SingleItemData(item_id=94, name='Twilight Dew', classification=ItemClassification.filler),
    SingleItemData(item_id=95, name='Bear Cicada', classification=ItemClassification.filler),
    SingleItemData(item_id=96, name='Azure Dragonfly', classification=ItemClassification.filler),
    SingleItemData(item_id=97, name='Veggie Set', classification=ItemClassification.filler),
    SingleItemData(item_id=98, name='Fruit Set', classification=ItemClassification.filler),
    SingleItemData(item_id=99, name='Junk Metal', classification=ItemClassification.filler),
    SingleItemData(item_id=100, name='Spiral Gem', classification=ItemClassification.filler),
    SingleItemData(item_id=101, name='Sparkly Boots', classification=ItemClassification.filler),
    SingleItemData(item_id=102, name="Gunner's Trigger", classification=ItemClassification.useful),
    SingleItemData(item_id=103, name='Feather Leaf', classification=ItemClassification.filler),
    SingleItemData(item_id=104, name='Rusty Bits', classification=ItemClassification.filler),
    SingleItemData(item_id=105, name='Frozen Tear', classification=ItemClassification.filler),
    SingleItemData(item_id=106, name='Pike Wood', classification=ItemClassification.filler),
    SingleItemData(item_id=107, name='Purple Ore Lump', classification=ItemClassification.filler),
    SingleItemData(item_id=108, name='Winter Thorn', classification=ItemClassification.filler),
    SingleItemData(item_id=109, name='Bergen Ice', classification=ItemClassification.filler),
    SingleItemData(item_id=110, name='Bergen Ice Cream', classification=ItemClassification.filler),
    SingleItemData(item_id=111, name='Battered Fist', classification=ItemClassification.useful),
    SingleItemData(item_id=112, name='Copper Gull', classification=ItemClassification.useful),
    SingleItemData(item_id=113, name='Iron Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=114, name='Rocksplitter', classification=ItemClassification.useful),
    SingleItemData(item_id=115, name='Silver Hawk', classification=ItemClassification.useful),
    SingleItemData(item_id=116, name='Cooling Veil', classification=ItemClassification.useful),
    SingleItemData(item_id=117, name='Longears', classification=ItemClassification.useful),
    SingleItemData(item_id=118, name='Iron Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=119, name='Furry Cap', classification=ItemClassification.useful),
    SingleItemData(item_id=120, name='Icewalkers', classification=ItemClassification.useful),
    SingleItemData(item_id=121, name='Iron Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=122, name='Iron Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=123, name='Hardrock Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=124, name='Spiky Jacket', classification=ItemClassification.useful),
    SingleItemData(item_id=125, name='Bubblebelt', classification=ItemClassification.useful),
    SingleItemData(item_id=126, name='Fluffy Fur', classification=ItemClassification.filler),
    SingleItemData(item_id=127, name='Rock Beak', classification=ItemClassification.filler),
    SingleItemData(item_id=128, name='Solid Bubble', classification=ItemClassification.filler),
    SingleItemData(item_id=129, name='Dropped Mic', classification=ItemClassification.filler),
    SingleItemData(item_id=130, name='Spice Set', classification=ItemClassification.filler),
    SingleItemData(item_id=131, name='The End', classification=ItemClassification.progression),
    SingleItemData(item_id=132, name='Echo Roll', classification=ItemClassification.filler),
    SingleItemData(item_id=133, name='Broken Gauntlet', classification=ItemClassification.progression),
    SingleItemData(item_id=135, name='Disc of Insight', classification=ItemClassification.progression),
    SingleItemData(item_id=136, name='Disc of Treasure', classification=ItemClassification.progression),
    SingleItemData(item_id=137, name='Broken Shield', classification=ItemClassification.progression),
    SingleItemData(item_id=138, name='Autumn Ingredients', classification=ItemClassification.progression),
    SingleItemData(item_id=139, name='Frosted Carrot', classification=ItemClassification.filler),
    SingleItemData(item_id=140, name='Perforated Tophat', classification=ItemClassification.filler),
    SingleItemData(item_id=141, name='Diabolic Horns', classification=ItemClassification.filler),
    SingleItemData(item_id=142, name='Captured Bunny', classification=ItemClassification.progression),
    SingleItemData(item_id=143, name='Disciple Gloves', classification=ItemClassification.useful),
    SingleItemData(item_id=144, name='Capture Device', classification=ItemClassification.progression),
    SingleItemData(item_id=145, name='Green Leaf Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=146, name="Faj'ro Key", classification=ItemClassification.progression),
    SingleItemData(item_id=147, name="Faj'ro Master Key", classification=ItemClassification.progression),
    SingleItemData(item_id=148, name='Yellow Sand Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=149, name='Mine Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=150, name='Neutral Stone', classification=ItemClassification.progression),
    SingleItemData(item_id=151, name='Hermit Repairkit', classification=ItemClassification.progression),
    SingleItemData(item_id=152, name='Mine Key', classification=ItemClassification.progression),
    SingleItemData(item_id=153, name='Mine Master Key', classification=ItemClassification.progression),
    SingleItemData(item_id=154, name="Thief's Key", classification=ItemClassification.progression),
    SingleItemData(item_id=155, name='White Key', classification=ItemClassification.progression),
    SingleItemData(item_id=156, name='Radiant Key', classification=ItemClassification.progression),
    SingleItemData(item_id=157, name="Ye dirty 'ol cheater", classification=ItemClassification.progression),
    SingleItemData(item_id=158, name='Stone of Valor', classification=ItemClassification.progression),
    SingleItemData(item_id=159, name='Bug Shell', classification=ItemClassification.filler),
    SingleItemData(item_id=160, name='Blue Orb', classification=ItemClassification.filler),
    SingleItemData(item_id=161, name='Proper Tophat', classification=ItemClassification.useful),
    SingleItemData(item_id=163, name='Metal Gears', classification=ItemClassification.filler),
    SingleItemData(item_id=164, name='Ancient Sandals', classification=ItemClassification.useful),
    SingleItemData(item_id=165, name='Sweet Lemonjuice', classification=ItemClassification.filler),
    SingleItemData(item_id=166, name='Hotsauce', classification=ItemClassification.filler),
    SingleItemData(item_id=167, name='Vanilla Ice Cream', classification=ItemClassification.filler),
    SingleItemData(item_id=168, name='Holiday Hat', classification=ItemClassification.filler),
    SingleItemData(item_id=169, name='Holiday Present', classification=ItemClassification.progression),
    SingleItemData(item_id=170, name='Guild Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=171, name='Pure Autumn Cider', classification=ItemClassification.progression),
    SingleItemData(item_id=172, name='Geo-Data #3469', classification=ItemClassification.progression),
    SingleItemData(item_id=173, name='Autumn Probe', classification=ItemClassification.progression),
    SingleItemData(item_id=174, name='Tough Sand', classification=ItemClassification.filler),
    SingleItemData(item_id=175, name='Glaring Rock', classification=ItemClassification.filler),
    SingleItemData(item_id=176, name='Rainbow Gem', classification=ItemClassification.filler),
    SingleItemData(item_id=177, name='Vivid Water', classification=ItemClassification.filler),
    SingleItemData(item_id=178, name='Palmapple Seed', classification=ItemClassification.filler),
    SingleItemData(item_id=179, name='Cactone Fruit', classification=ItemClassification.filler),
    SingleItemData(item_id=180, name='Old Bones', classification=ItemClassification.filler),
    SingleItemData(item_id=181, name='Helix Relic', classification=ItemClassification.filler),
    SingleItemData(item_id=182, name='Lucid Shard', classification=ItemClassification.filler),
    SingleItemData(item_id=183, name='Everlasting Amber', classification=ItemClassification.filler),
    SingleItemData(item_id=184, name='Weird Hillkat Tech', classification=ItemClassification.progression),
    SingleItemData(item_id=185, name='Crystal Leek', classification=ItemClassification.filler),
    SingleItemData(item_id=186, name='Arid Lumber', classification=ItemClassification.filler),
    SingleItemData(item_id=187, name='Ancient Earth', classification=ItemClassification.filler),
    SingleItemData(item_id=188, name='Maroon Chestnut', classification=ItemClassification.filler),
    SingleItemData(item_id=189, name='Autumn Salve', classification=ItemClassification.progression),
    SingleItemData(item_id=190, name='Refined Metal', classification=ItemClassification.filler),
    SingleItemData(item_id=191, name='Precious Metal', classification=ItemClassification.filler),
    SingleItemData(item_id=192, name='Epic Metal', classification=ItemClassification.filler),
    SingleItemData(item_id=193, name='Gourmet Steak', classification=ItemClassification.filler),
    SingleItemData(item_id=194, name='Poison Stinger', classification=ItemClassification.filler),
    SingleItemData(item_id=195, name='Drill Stone', classification=ItemClassification.filler),
    SingleItemData(item_id=196, name='Dry Fin', classification=ItemClassification.filler),
    SingleItemData(item_id=197, name='Squishy Teeth', classification=ItemClassification.filler),
    SingleItemData(item_id=198, name='Hardened Liver', classification=ItemClassification.filler),
    SingleItemData(item_id=199, name='Phoenix Feather', classification=ItemClassification.filler),
    SingleItemData(item_id=200, name='Butter Silk', classification=ItemClassification.filler),
    SingleItemData(item_id=201, name='Jelly Extract', classification=ItemClassification.filler),
    SingleItemData(item_id=202, name='Magma Residue', classification=ItemClassification.filler),
    SingleItemData(item_id=203, name='Laser Eyes', classification=ItemClassification.filler),
    SingleItemData(item_id=204, name='Steel Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=205, name='Steel Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=206, name='Steel Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=207, name='Steel Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=208, name='Fin Cap', classification=ItemClassification.useful),
    SingleItemData(item_id=209, name='Rapier Carrot', classification=ItemClassification.useful),
    SingleItemData(item_id=210, name='Dessert Vest', classification=ItemClassification.useful),
    SingleItemData(item_id=211, name='Desert Sandals', classification=ItemClassification.useful),
    SingleItemData(item_id=212, name='Nomadic Turban', classification=ItemClassification.useful),
    SingleItemData(item_id=213, name='Chilling Veil', classification=ItemClassification.useful),
    SingleItemData(item_id=214, name='Shiny Glasses', classification=ItemClassification.useful),
    SingleItemData(item_id=215, name='Magic Robe', classification=ItemClassification.useful),
    SingleItemData(item_id=216, name='Assassin Garb', classification=ItemClassification.useful),
    SingleItemData(item_id=217, name='Crystal Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=218, name='Curly Slippers', classification=ItemClassification.useful),
    SingleItemData(item_id=219, name='Lavish Anchors', classification=ItemClassification.useful),
    SingleItemData(item_id=220, name='Carpet Runners', classification=ItemClassification.useful),
    SingleItemData(item_id=221, name='Hidden Blade', classification=ItemClassification.useful),
    SingleItemData(item_id=222, name='Maverick Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=223, name='Western Starfist', classification=ItemClassification.useful),
    SingleItemData(item_id=224, name='Bergen Probe', classification=ItemClassification.progression),
    SingleItemData(item_id=225, name='Blue Ice Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=226, name='Steak, rare', classification=ItemClassification.filler),
    SingleItemData(item_id=227, name='Stone of Space', classification=ItemClassification.progression),
    SingleItemData(item_id=228, name="Thief's Band", classification=ItemClassification.useful),
    SingleItemData(item_id=229, name='Mighty Strand', classification=ItemClassification.useful),
    SingleItemData(item_id=230, name='Red Flame Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=231, name='Purple Bolt Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=233, name='Meister Gloves', classification=ItemClassification.useful),
    SingleItemData(item_id=234, name='Aspiration Proof', classification=ItemClassification.progression),
    SingleItemData(item_id=235, name='Wooly Socks', classification=ItemClassification.useful),
    SingleItemData(item_id=236, name='Maroon Cave Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=237, name='Shiny Orb', classification=ItemClassification.progression),
    SingleItemData(item_id=238, name='Laser Pickaxe', classification=ItemClassification.progression),
    SingleItemData(item_id=239, name='Laser TNT', classification=ItemClassification.progression),
    SingleItemData(item_id=240, name='Mining Docs', classification=ItemClassification.progression),
    SingleItemData(item_id=241, name='Parched Leaves', classification=ItemClassification.filler),
    SingleItemData(item_id=242, name='Ripe Apples', classification=ItemClassification.filler),
    SingleItemData(item_id=243, name='White Grain', classification=ItemClassification.filler),
    SingleItemData(item_id=244, name='Sunset Dew', classification=ItemClassification.filler),
    SingleItemData(item_id=245, name='Wolf Cicada', classification=ItemClassification.filler),
    SingleItemData(item_id=246, name='Crimson Dragonfly', classification=ItemClassification.filler),
    SingleItemData(item_id=248, name='Flintzer Excretions', classification=ItemClassification.progression),
    SingleItemData(item_id=249, name='Curly Fern', classification=ItemClassification.filler),
    SingleItemData(item_id=250, name='Steel Comb', classification=ItemClassification.filler),
    SingleItemData(item_id=251, name='Elder Wood', classification=ItemClassification.filler),
    SingleItemData(item_id=252, name='Venom Shroom', classification=ItemClassification.filler),
    SingleItemData(item_id=253, name='Glowing Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=254, name='Virus Root', classification=ItemClassification.filler),
    SingleItemData(item_id=255, name='Blue Mango', classification=ItemClassification.filler),
    SingleItemData(item_id=256, name='Exotic Resin', classification=ItemClassification.filler),
    SingleItemData(item_id=257, name='Star Fruit', classification=ItemClassification.filler),
    SingleItemData(item_id=258, name='Common Planter', classification=ItemClassification.filler),
    SingleItemData(item_id=259, name='Spiky Nut', classification=ItemClassification.filler),
    SingleItemData(item_id=260, name='Moon Fruit', classification=ItemClassification.filler),
    SingleItemData(item_id=261, name='Galaxy Berry', classification=ItemClassification.filler),
    SingleItemData(item_id=262, name='Royal Hive', classification=ItemClassification.filler),
    SingleItemData(item_id=263, name='Progression Proof', classification=ItemClassification.progression),
    SingleItemData(item_id=264, name='Silver Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=265, name='Titan Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=266, name='Silver Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=267, name='Titan Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=268, name='Silver Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=269, name='Titan Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=270, name='Silver Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=271, name='Titan Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=272, name="Zir'vitar Key", classification=ItemClassification.progression),
    SingleItemData(item_id=273, name='GIT', classification=ItemClassification.progression),
    SingleItemData(item_id=274, name='Static Furball', classification=ItemClassification.filler),
    SingleItemData(item_id=275, name='Slime Drop', classification=ItemClassification.filler),
    SingleItemData(item_id=276, name='Palette Blossom', classification=ItemClassification.filler),
    SingleItemData(item_id=277, name='Huge Nut', classification=ItemClassification.filler),
    SingleItemData(item_id=278, name='Lazy Claw', classification=ItemClassification.filler),
    SingleItemData(item_id=279, name='Stout Backplate', classification=ItemClassification.filler),
    SingleItemData(item_id=280, name='Power Spinach', classification=ItemClassification.filler),
    SingleItemData(item_id=281, name='Living Bolt', classification=ItemClassification.filler),
    SingleItemData(item_id=282, name='Metal Down', classification=ItemClassification.filler),
    SingleItemData(item_id=283, name='Plain Cube', classification=ItemClassification.filler),
    SingleItemData(item_id=284, name='Glow Pear', classification=ItemClassification.filler),
    SingleItemData(item_id=285, name='Disc of Flora', classification=ItemClassification.progression),
    SingleItemData(item_id=286, name='Azure Drop Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=287, name='Strawhat', classification=ItemClassification.useful),
    SingleItemData(item_id=288, name='Gaia Temple Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=289, name='Prime Pistachios', classification=ItemClassification.filler),
    SingleItemData(item_id=290, name='Salted Peanuts', classification=ItemClassification.filler),
    SingleItemData(item_id=291, name="Cup o' Coffee", classification=ItemClassification.filler),
    SingleItemData(item_id=292, name='Energy Espresso', classification=ItemClassification.filler),
    SingleItemData(item_id=293, name='Nifty Grey Shades', classification=ItemClassification.useful),
    SingleItemData(item_id=294, name='Red Bandana', classification=ItemClassification.useful),
    SingleItemData(item_id=295, name="Electrician's Cap", classification=ItemClassification.useful),
    SingleItemData(item_id=296, name='Faedora', classification=ItemClassification.useful),
    SingleItemData(item_id=297, name='Mystic Mohawk', classification=ItemClassification.useful),
    SingleItemData(item_id=298, name="Hunter's Bolt", classification=ItemClassification.useful),
    SingleItemData(item_id=299, name="Lawkeeper's Fist", classification=ItemClassification.useful),
    SingleItemData(item_id=300, name='Aehre', classification=ItemClassification.useful),
    SingleItemData(item_id=301, name='Twitching Slicer', classification=ItemClassification.useful),
    SingleItemData(item_id=302, name='Sunset Claw', classification=ItemClassification.useful),
    SingleItemData(item_id=303, name='Sneaky Shiv', classification=ItemClassification.useful),
    SingleItemData(item_id=304, name='Ramming Shell', classification=ItemClassification.useful),
    SingleItemData(item_id=305, name='Survival Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=306, name='Rootweave', classification=ItemClassification.useful),
    SingleItemData(item_id=307, name='Petal Cloak', classification=ItemClassification.useful),
    SingleItemData(item_id=308, name='Loose Trenchcoat', classification=ItemClassification.useful),
    SingleItemData(item_id=309, name='Stable Footguard', classification=ItemClassification.useful),
    SingleItemData(item_id=310, name='Hydraulic Anchors', classification=ItemClassification.useful),
    SingleItemData(item_id=311, name='Shinkickers', classification=ItemClassification.useful),
    SingleItemData(item_id=312, name='Urban Sneakers', classification=ItemClassification.useful),
    SingleItemData(item_id=313, name='Pathfinders', classification=ItemClassification.useful),
    SingleItemData(item_id=314, name='Sea Disc', classification=ItemClassification.filler),
    SingleItemData(item_id=315, name='Maultasche', classification=ItemClassification.filler),
    SingleItemData(item_id=316, name='Werewolf Stick', classification=ItemClassification.filler),
    SingleItemData(item_id=317, name='Food Temp #3', classification=ItemClassification.progression),
    SingleItemData(item_id=318, name='Food Temp #4', classification=ItemClassification.progression),
    SingleItemData(item_id=319, name="So'najiz Key", classification=ItemClassification.progression),
    SingleItemData(item_id=320, name="Jack's Flame", classification=ItemClassification.progression),
    SingleItemData(item_id=321, name='Aged Travelguide', classification=ItemClassification.progression),
    SingleItemData(item_id=322, name='Galaxy Spiral Drill', classification=ItemClassification.useful),
    SingleItemData(item_id=323, name='Infinity Spiral Drill', classification=ItemClassification.useful),
    SingleItemData(item_id=324, name='Stone of Truth', classification=ItemClassification.progression),
    SingleItemData(item_id=325, name='Creation Gem', classification=ItemClassification.filler),
    SingleItemData(item_id=326, name="King's Ring", classification=ItemClassification.filler),
    SingleItemData(item_id=327, name='Golden Revolver', classification=ItemClassification.useful),
    SingleItemData(item_id=328, name="Bandit's Scarf", classification=ItemClassification.useful),
    SingleItemData(item_id=329, name="Burglar's Rope", classification=ItemClassification.useful),
    SingleItemData(item_id=330, name='Excalibro', classification=ItemClassification.useful),
    SingleItemData(item_id=331, name='Snack Mix', classification=ItemClassification.filler),
    SingleItemData(item_id=332, name='Rough Branch', classification=ItemClassification.useful),
    SingleItemData(item_id=333, name='Bigger Stick', classification=ItemClassification.useful),
    SingleItemData(item_id=334, name='Goddess Plume', classification=ItemClassification.filler),
    SingleItemData(item_id=335, name='Cold Platter', classification=ItemClassification.filler),
    SingleItemData(item_id=336, name='Full Course', classification=ItemClassification.filler),
    SingleItemData(item_id=337, name='Bronze Chest Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=338, name='Silver Chest Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=339, name='Golden Chest Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=340, name='Hungry Salmon', classification=ItemClassification.filler),
    SingleItemData(item_id=341, name='Plate of Chests', classification=ItemClassification.useful),
    SingleItemData(item_id=342, name="Billston's Com", classification=ItemClassification.progression),
    SingleItemData(item_id=343, name='Smokaway', classification=ItemClassification.progression),
    SingleItemData(item_id=344, name='Tracker Chip', classification=ItemClassification.progression),
    SingleItemData(item_id=345, name='Pond Slums Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=346, name='One Up', classification=ItemClassification.filler),
    SingleItemData(item_id=347, name='Maroon Probe', classification=ItemClassification.progression),
    SingleItemData(item_id=348, name='Polished Mic', classification=ItemClassification.filler),
    SingleItemData(item_id=349, name="Krys'kajo Key", classification=ItemClassification.progression),
    SingleItemData(item_id=350, name='Kajo Master Key', classification=ItemClassification.progression),
    SingleItemData(item_id=351, name='Warkeeper', classification=ItemClassification.useful),
    SingleItemData(item_id=352, name='Ambiguous Rod', classification=ItemClassification.filler),
    SingleItemData(item_id=353, name='Kebab Roll', classification=ItemClassification.filler),
    SingleItemData(item_id=354, name='Wrap Roll', classification=ItemClassification.filler),
    SingleItemData(item_id=355, name='Meaty Risotto', classification=ItemClassification.filler),
    SingleItemData(item_id=356, name='Shrimp Risotto', classification=ItemClassification.filler),
    SingleItemData(item_id=357, name='Green Risotto', classification=ItemClassification.filler),
    SingleItemData(item_id=358, name='Final Dinner', classification=ItemClassification.filler),
    SingleItemData(item_id=359, name='Tattered Satchel', classification=ItemClassification.useful),
    SingleItemData(item_id=360, name='Prism Pouch', classification=ItemClassification.useful),
    SingleItemData(item_id=361, name='Infinite Bag', classification=ItemClassification.useful),
    SingleItemData(item_id=362, name="Ti'im Residue", classification=ItemClassification.progression),
    SingleItemData(item_id=363, name='Adept Gloves', classification=ItemClassification.useful),
    SingleItemData(item_id=364, name='Storage Unit #1', classification=ItemClassification.progression),
    SingleItemData(item_id=365, name='Scouting Visor', classification=ItemClassification.useful),
    SingleItemData(item_id=366, name='Just Water', classification=ItemClassification.filler),
    SingleItemData(item_id=367, name='Bear Beer', classification=ItemClassification.filler),
    SingleItemData(item_id=368, name='Crab Mead', classification=ItemClassification.filler),
    SingleItemData(item_id=369, name='Fox Sake', classification=ItemClassification.filler),
    SingleItemData(item_id=370, name='Whale Wine', classification=ItemClassification.filler),
    SingleItemData(item_id=371, name='Brewing Kit', classification=ItemClassification.progression),
    SingleItemData(item_id=372, name='Brewing Kit: Bear', classification=ItemClassification.filler),
    SingleItemData(item_id=373, name='Brewing Kit: Crab', classification=ItemClassification.filler),
    SingleItemData(item_id=374, name='Brewing Kit: Fox', classification=ItemClassification.filler),
    SingleItemData(item_id=375, name='Brewing Kit: Whale', classification=ItemClassification.filler),
    SingleItemData(item_id=376, name='Green Seed Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=377, name='Gaia Probe', classification=ItemClassification.progression),
    SingleItemData(item_id=378, name="Old Man's Book", classification=ItemClassification.progression),
    SingleItemData(item_id=379, name='Crystal Water', classification=ItemClassification.filler),
    SingleItemData(item_id=380, name='Mysterious Box', classification=ItemClassification.filler),
    SingleItemData(item_id=381, name='Tremor Engine', classification=ItemClassification.filler),
    SingleItemData(item_id=382, name='Rising Super Star', classification=ItemClassification.filler),
    SingleItemData(item_id=383, name='Blue Grass', classification=ItemClassification.filler),
    SingleItemData(item_id=384, name='Pink Petal', classification=ItemClassification.filler),
    SingleItemData(item_id=385, name='Mystery Grape', classification=ItemClassification.filler),
    SingleItemData(item_id=386, name='Green Arbor', classification=ItemClassification.filler),
    SingleItemData(item_id=387, name='Catalop Pellet', classification=ItemClassification.filler),
    SingleItemData(item_id=388, name='Steel Bamboo', classification=ItemClassification.filler),
    SingleItemData(item_id=389, name='Dirty Rubble', classification=ItemClassification.filler),
    SingleItemData(item_id=390, name='Spark Tin', classification=ItemClassification.filler),
    SingleItemData(item_id=391, name='Cobalt Crystal', classification=ItemClassification.filler),
    SingleItemData(item_id=392, name='Dream Globe', classification=ItemClassification.filler),
    SingleItemData(item_id=393, name='Cobalt Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=394, name='Cobalt Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=395, name='Cobalt Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=396, name='Cobalt Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=397, name='Laser Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=398, name='Laser Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=399, name='Laser Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=400, name='Laser Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=401, name='Infected Cell', classification=ItemClassification.filler),
    SingleItemData(item_id=402, name='Elemental DNA', classification=ItemClassification.filler),
    SingleItemData(item_id=403, name='Cursed Coin', classification=ItemClassification.progression),
    SingleItemData(item_id=404, name='Broken Sword', classification=ItemClassification.progression),
    SingleItemData(item_id=405, name='Ronin Shell', classification=ItemClassification.filler),
    SingleItemData(item_id=406, name='Samurai Shell', classification=ItemClassification.filler),
    SingleItemData(item_id=407, name='Sharp Splitter', classification=ItemClassification.filler),
    SingleItemData(item_id=408, name='Hoverpad', classification=ItemClassification.filler),
    SingleItemData(item_id=409, name='Sticky Web', classification=ItemClassification.filler),
    SingleItemData(item_id=410, name='Star Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=411, name='Hardhead Hat', classification=ItemClassification.useful),
    SingleItemData(item_id=412, name="Survivor's Blade", classification=ItemClassification.useful),
    SingleItemData(item_id=413, name='Marksmen Trigger', classification=ItemClassification.useful),
    SingleItemData(item_id=414, name='Panzer Fist', classification=ItemClassification.useful),
    SingleItemData(item_id=415, name='Shadowy Cloak', classification=ItemClassification.useful),
    SingleItemData(item_id=416, name='Plated Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=417, name='Bamboots', classification=ItemClassification.useful),
    SingleItemData(item_id=418, name='Brave Anchors', classification=ItemClassification.useful),
    SingleItemData(item_id=419, name='Shuddering Cleaver', classification=ItemClassification.useful),
    SingleItemData(item_id=420, name='Tengu Mask', classification=ItemClassification.useful),
    SingleItemData(item_id=421, name='Sonic Spike', classification=ItemClassification.useful),
    SingleItemData(item_id=422, name='Lead Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=423, name='Omni Lock', classification=ItemClassification.filler),
    SingleItemData(item_id=424, name='Shining Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=425, name='Bluefiber Robe', classification=ItemClassification.useful),
    SingleItemData(item_id=426, name='Toggle Test', classification=ItemClassification.filler),
    SingleItemData(item_id=427, name='Stone Key', classification=ItemClassification.progression),
    SingleItemData(item_id=428, name='Circuit Override', classification=ItemClassification.progression),
    SingleItemData(item_id=429, name='F.A.I.R. Device', classification=ItemClassification.progression),
    SingleItemData(item_id=430, name='Smelter Parts', classification=ItemClassification.progression),
    SingleItemData(item_id=431, name='Marinated Meat', classification=ItemClassification.filler),
    SingleItemData(item_id=432, name='Bright Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=433, name='Prickly Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=434, name='Meteor Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=435, name='Golden Bug', classification=ItemClassification.progression),
    SingleItemData(item_id=436, name='Sparkling Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=438, name='Brostick of Force', classification=ItemClassification.useful),
    SingleItemData(item_id=439, name='Old Dojo Key', classification=ItemClassification.progression),
    SingleItemData(item_id=440, name='Twilight Shard', classification=ItemClassification.filler),
    SingleItemData(item_id=441, name='Old Geta', classification=ItemClassification.useful),
    SingleItemData(item_id=443, name='Broken Deck', classification=ItemClassification.progression),
    SingleItemData(item_id=444, name='Stone of Spirit', classification=ItemClassification.progression),
    SingleItemData(item_id=445, name='Infinity Gem', classification=ItemClassification.filler),
    SingleItemData(item_id=446, name='Stone of Ages', classification=ItemClassification.progression),
    SingleItemData(item_id=447, name="Heaven's Seed", classification=ItemClassification.filler),
    SingleItemData(item_id=448, name='Rise Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=449, name='Fall Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=450, name='Trail Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=451, name='Valley Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=452, name='Garden Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=453, name='Ridge Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=454, name='Halcyon Droplet', classification=ItemClassification.filler),
    SingleItemData(item_id=455, name='Portrait of Ruin', classification=ItemClassification.filler),
    SingleItemData(item_id=456, name='Very Large Ember', classification=ItemClassification.progression),
    SingleItemData(item_id=457, name='Ruby', classification=ItemClassification.filler),
    SingleItemData(item_id=458, name='Garnet', classification=ItemClassification.filler),
    SingleItemData(item_id=459, name='Diamond', classification=ItemClassification.filler),
    SingleItemData(item_id=460, name='Moonstone', classification=ItemClassification.filler),
    SingleItemData(item_id=461, name='Citrine', classification=ItemClassification.filler),
    SingleItemData(item_id=462, name='Topaz', classification=ItemClassification.filler),
    SingleItemData(item_id=463, name='Amethyst', classification=ItemClassification.filler),
    SingleItemData(item_id=464, name='Emerald', classification=ItemClassification.filler),
    SingleItemData(item_id=465, name='Lapis Lazuli', classification=ItemClassification.filler),
    SingleItemData(item_id=466, name='Mine Detector', classification=ItemClassification.filler),
    SingleItemData(item_id=467, name='Dried Grass Hat', classification=ItemClassification.useful),
    SingleItemData(item_id=468, name='Strawberry Hat', classification=ItemClassification.useful),
    SingleItemData(item_id=469, name='The Last Strawhat', classification=ItemClassification.useful),
    SingleItemData(item_id=470, name='Climate Cowl', classification=ItemClassification.useful),
    SingleItemData(item_id=471, name='Serene Bubble', classification=ItemClassification.useful),
    SingleItemData(item_id=472, name='Furious Hothead', classification=ItemClassification.useful),
    SingleItemData(item_id=473, name='Trackwalker Visor', classification=ItemClassification.useful),
    SingleItemData(item_id=474, name='Skirmisher', classification=ItemClassification.useful),
    SingleItemData(item_id=475, name='Unbreaking Fist', classification=ItemClassification.useful),
    SingleItemData(item_id=476, name='Golden Falcon', classification=ItemClassification.useful),
    SingleItemData(item_id=477, name='Zealous Lamellar ', classification=ItemClassification.useful),
    SingleItemData(item_id=478, name='Pioneer Vest', classification=ItemClassification.useful),
    SingleItemData(item_id=479, name='Reactive Plate', classification=ItemClassification.useful),
    SingleItemData(item_id=480, name='Vermillion Mantle', classification=ItemClassification.useful),
    SingleItemData(item_id=481, name='Deadly Dancers', classification=ItemClassification.useful),
    SingleItemData(item_id=482, name='Praetorian Anchors', classification=ItemClassification.useful),
    SingleItemData(item_id=483, name='Mistwalkers', classification=ItemClassification.useful),
    SingleItemData(item_id=484, name='Geta Wood', classification=ItemClassification.filler),
    SingleItemData(item_id=485, name='Geta Straps', classification=ItemClassification.filler),
    SingleItemData(item_id=486, name='Geta Glue', classification=ItemClassification.filler),
    SingleItemData(item_id=487, name='Golden Satchel', classification=ItemClassification.filler),
    SingleItemData(item_id=488, name='Golden Bars', classification=ItemClassification.filler),
    SingleItemData(item_id=489, name='Golden Ticket', classification=ItemClassification.filler),
    SingleItemData(item_id=490, name='Dk Pepper', classification=ItemClassification.filler),
    SingleItemData(item_id=491, name='Cheese Spaetzle', classification=ItemClassification.filler),
    SingleItemData(item_id=493, name='Durian', classification=ItemClassification.filler),
    SingleItemData(item_id=494, name='PengoPop', classification=ItemClassification.filler),
    SingleItemData(item_id=495, name='Spicy Beat-0-Type', classification=ItemClassification.filler),
    SingleItemData(item_id=496, name='Guacamole Toast', classification=ItemClassification.filler),
    SingleItemData(item_id=497, name='Old Blueprint', classification=ItemClassification.progression),
    SingleItemData(item_id=498, name='Kunoichi', classification=ItemClassification.filler),
    SingleItemData(item_id=499, name='Antique Token', classification=ItemClassification.filler),
    SingleItemData(item_id=500, name='Radiant Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=501, name='Chest Detector', classification=ItemClassification.filler),
    SingleItemData(item_id=502, name='Moistured Line', classification=ItemClassification.filler),
    SingleItemData(item_id=503, name='Trash', classification=ItemClassification.filler),
    SingleItemData(item_id=504, name='Thrashing Ripper', classification=ItemClassification.useful),
    SingleItemData(item_id=505, name='Rusty Hook', classification=ItemClassification.filler),
    SingleItemData(item_id=506, name='Gorgon Veil', classification=ItemClassification.useful),
    SingleItemData(item_id=507, name='Centaur Vest', classification=ItemClassification.useful),
    SingleItemData(item_id=508, name='Unicorn Greaves', classification=ItemClassification.useful),
    SingleItemData(item_id=509, name='Chestlink', classification=ItemClassification.filler),
    SingleItemData(item_id=510, name='Lifefiber Uniform', classification=ItemClassification.useful),
    SingleItemData(item_id=511, name='Infinity+1 Bag', classification=ItemClassification.useful),
    SingleItemData(item_id=512, name='Mantis Whip', classification=ItemClassification.useful),
    SingleItemData(item_id=513, name='Nanopoint Needle', classification=ItemClassification.useful),
    SingleItemData(item_id=514, name='Roundhousers', classification=ItemClassification.useful),
    SingleItemData(item_id=515, name='Broken Chakrams', classification=ItemClassification.progression),
    SingleItemData(item_id=516, name='Mooncake', classification=ItemClassification.filler),
    SingleItemData(item_id=517, name='Turret Tokens', classification=ItemClassification.filler),
    SingleItemData(item_id=518, name='Trench Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=519, name='Element Aura', classification=ItemClassification.filler),
    SingleItemData(item_id=520, name='Menacing Aura', classification=ItemClassification.filler),
    SingleItemData(item_id=521, name='Chunky', classification=ItemClassification.filler),
    SingleItemData(item_id=522, name='Paedalos', classification=ItemClassification.useful),
    SingleItemData(item_id=523, name='Killing Dress', classification=ItemClassification.useful),
    SingleItemData(item_id=524, name='Pendulum Striker', classification=ItemClassification.useful),
    SingleItemData(item_id=525, name='Knocking One', classification=ItemClassification.useful),
    SingleItemData(item_id=526, name="Dragon's Bandana", classification=ItemClassification.useful),
    SingleItemData(item_id=527, name='Orange Twister', classification=ItemClassification.filler),
    SingleItemData(item_id=528, name='Baby Peng', classification=ItemClassification.filler),
    SingleItemData(item_id=529, name='FDNI Fox', classification=ItemClassification.filler),
    SingleItemData(item_id=530, name='Eternal Salami', classification=ItemClassification.useful),
    SingleItemData(item_id=531, name='Assault Harness', classification=ItemClassification.useful),
    SingleItemData(item_id=532, name='Tranquil Earmuffs', classification=ItemClassification.useful),
    SingleItemData(item_id=533, name='Combat Skates', classification=ItemClassification.useful),
    SingleItemData(item_id=534, name='Good Boy', classification=ItemClassification.filler),
    SingleItemData(item_id=535, name='Coarse Powerring', classification=ItemClassification.progression),
    SingleItemData(item_id=536, name='Artillery Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=537, name='S-Rex', classification=ItemClassification.filler),
    SingleItemData(item_id=538, name="Lil' Reap", classification=ItemClassification.filler),
    SingleItemData(item_id=539, name='Red Liz', classification=ItemClassification.filler),
    SingleItemData(item_id=540, name='Encrypted Key', classification=ItemClassification.progression),
    SingleItemData(item_id=541, name='Facility X Key', classification=ItemClassification.progression),
    SingleItemData(item_id=542, name='Supercrown', classification=ItemClassification.progression),
    SingleItemData(item_id=543, name='Snowtank Datachip', classification=ItemClassification.progression),
    SingleItemData(item_id=544, name='Fishy Documents', classification=ItemClassification.progression),
    SingleItemData(item_id=545, name='Hightech Valve', classification=ItemClassification.progression),
    SingleItemData(item_id=546, name='Shy Fly', classification=ItemClassification.filler),
    SingleItemData(item_id=547, name='T.A.N.K.', classification=ItemClassification.filler),
    SingleItemData(item_id=548, name='Micro Crawler', classification=ItemClassification.filler),
    SingleItemData(item_id=549, name='Cool Bar', classification=ItemClassification.filler),
    SingleItemData(item_id=550, name='Ascension Proof', classification=ItemClassification.progression),
    SingleItemData(item_id=551, name='Willis Waldmahl', classification=ItemClassification.filler),
    SingleItemData(item_id=552, name='Batboy', classification=ItemClassification.filler),
    SingleItemData(item_id=553, name='Butterfliege', classification=ItemClassification.filler),
    SingleItemData(item_id=554, name='Piggybank', classification=ItemClassification.filler),
    SingleItemData(item_id=555, name='Seedling', classification=ItemClassification.filler),
    SingleItemData(item_id=556, name='Turbo', classification=ItemClassification.filler),
    SingleItemData(item_id=557, name='I Rob-0T', classification=ItemClassification.filler),
    SingleItemData(item_id=558, name='Baby of the East', classification=ItemClassification.filler),
    SingleItemData(item_id=559, name='Goose', classification=ItemClassification.filler),
    SingleItemData(item_id=560, name="Ku'lero Key", classification=ItemClassification.progression),
    SingleItemData(item_id=561, name='Strange Shard', classification=ItemClassification.filler),
    SingleItemData(item_id=562, name='Cone Seed', classification=ItemClassification.filler),
    SingleItemData(item_id=563, name='Antique Ore', classification=ItemClassification.filler),
    SingleItemData(item_id=564, name='Rose Cone', classification=ItemClassification.filler),
    SingleItemData(item_id=565, name='Salty Grass', classification=ItemClassification.filler),
    SingleItemData(item_id=566, name='Coral Piece', classification=ItemClassification.filler),
    SingleItemData(item_id=567, name='Cross Edge', classification=ItemClassification.useful),
    SingleItemData(item_id=568, name='Cross Goggles', classification=ItemClassification.useful),
    SingleItemData(item_id=569, name='Cross Mail', classification=ItemClassification.useful),
    SingleItemData(item_id=570, name='Cross Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=571, name='Serene Bubble+', classification=ItemClassification.useful),
    SingleItemData(item_id=572, name='Furious Hothead+', classification=ItemClassification.useful),
    SingleItemData(item_id=573, name='Trackwalker Visor+', classification=ItemClassification.useful),
    SingleItemData(item_id=574, name='Medusa Veil', classification=ItemClassification.useful),
    SingleItemData(item_id=575, name="Dragon's Bandana+", classification=ItemClassification.useful),
    SingleItemData(item_id=576, name='Tranquil Earmuffs+', classification=ItemClassification.useful),
    SingleItemData(item_id=577, name='Skirmisher+', classification=ItemClassification.useful),
    SingleItemData(item_id=578, name='Unbreaking Fist+', classification=ItemClassification.useful),
    SingleItemData(item_id=579, name='Mantis Whip+', classification=ItemClassification.useful),
    SingleItemData(item_id=580, name='Golden Falcon+', classification=ItemClassification.useful),
    SingleItemData(item_id=581, name='Brostick of Force+', classification=ItemClassification.useful),
    SingleItemData(item_id=582, name='Cerberus Fang', classification=ItemClassification.useful),
    SingleItemData(item_id=583, name='Zealous Lamellar+', classification=ItemClassification.useful),
    SingleItemData(item_id=584, name='Pioneer Vest+', classification=ItemClassification.useful),
    SingleItemData(item_id=585, name='Reactive Plate+', classification=ItemClassification.useful),
    SingleItemData(item_id=586, name='Chiron Vest', classification=ItemClassification.useful),
    SingleItemData(item_id=587, name='Killing Dress+', classification=ItemClassification.useful),
    SingleItemData(item_id=588, name='Assault Harness+', classification=ItemClassification.useful),
    SingleItemData(item_id=589, name='Pendulum Striker+', classification=ItemClassification.useful),
    SingleItemData(item_id=590, name='Knocking One+', classification=ItemClassification.useful),
    SingleItemData(item_id=592, name='Deadly Dancers+', classification=ItemClassification.useful),
    SingleItemData(item_id=593, name='Praetorian Anchors+', classification=ItemClassification.useful),
    SingleItemData(item_id=594, name='Mistwalkers+', classification=ItemClassification.useful),
    SingleItemData(item_id=595, name='Pegasus Greaves', classification=ItemClassification.useful),
    SingleItemData(item_id=596, name='Combat Skates+', classification=ItemClassification.useful),
    SingleItemData(item_id=597, name='Paedalos+', classification=ItemClassification.useful),
    SingleItemData(item_id=598, name='Very Last Strawhat', classification=ItemClassification.useful),
    SingleItemData(item_id=599, name='Sunshine Bracer', classification=ItemClassification.useful),
    SingleItemData(item_id=601, name='Highmeister Gloves', classification=ItemClassification.useful),
    SingleItemData(item_id=602, name='Body Armoire', classification=ItemClassification.useful),
    SingleItemData(item_id=603, name='Artillery Boots+', classification=ItemClassification.useful),
    SingleItemData(item_id=604, name='Lifefiber Dress', classification=ItemClassification.useful),
    SingleItemData(item_id=605, name='Eternal Salami+', classification=ItemClassification.useful),
    SingleItemData(item_id=606, name='Light Gem', classification=ItemClassification.filler),
    SingleItemData(item_id=607, name='Shuriken Shooter', classification=ItemClassification.useful),
    SingleItemData(item_id=608, name='Barrel Beak', classification=ItemClassification.filler),
    SingleItemData(item_id=609, name='Rumble Hive', classification=ItemClassification.filler),
    SingleItemData(item_id=610, name='Burned Ash', classification=ItemClassification.filler),
    SingleItemData(item_id=611, name='Speedy Boom Boots', classification=ItemClassification.useful),
    SingleItemData(item_id=612, name='Unruly Emeralds', classification=ItemClassification.filler),
    SingleItemData(item_id=618, name='Booster Booster', classification=ItemClassification.progression),
    SingleItemData(item_id=619, name='Yellow Sponge', classification=ItemClassification.filler),
    SingleItemData(item_id=620, name='Mellow Water', classification=ItemClassification.filler),
    SingleItemData(item_id=621, name='Shell Nut', classification=ItemClassification.filler),
    SingleItemData(item_id=622, name="MacGuffin's Coin", classification=ItemClassification.progression),
    SingleItemData(item_id=623, name='Gold Surprise Egg', classification=ItemClassification.filler),
    SingleItemData(item_id=624, name="Ku'lero Master Key", classification=ItemClassification.progression),
    SingleItemData(item_id=625, name='Ancient Cups', classification=ItemClassification.progression),
    SingleItemData(item_id=626, name='Full Rhombus Pass', classification=ItemClassification.progression),
    SingleItemData(item_id=627, name='Ancient Shade', classification=ItemClassification.progression),
    SingleItemData(item_id=628, name='Nuclear Roach', classification=ItemClassification.filler),
    SingleItemData(item_id=629, name='Core Stone', classification=ItemClassification.filler),
    SingleItemData(item_id=630, name='Worm Band', classification=ItemClassification.filler),
    SingleItemData(item_id=631, name='Ember Sack', classification=ItemClassification.filler),
    SingleItemData(item_id=632, name='Razor Tip', classification=ItemClassification.filler),
    SingleItemData(item_id=633, name='Focus Shard', classification=ItemClassification.filler),
    SingleItemData(item_id=634, name='Singularity Drill', classification=ItemClassification.useful),
    SingleItemData(item_id=635, name='Rift Spore', classification=ItemClassification.filler),
    SingleItemData(item_id=637, name='Pumpkin Spice Cof.', classification=ItemClassification.filler),
    SingleItemData(item_id=638, name='Tremor Core', classification=ItemClassification.progression),
    SingleItemData(item_id=639, name='Tremor Mirage', classification=ItemClassification.useful),
    SingleItemData(item_id=640, name="Champion's Towel", classification=ItemClassification.filler),
    SingleItemData(item_id=641, name='Dragon Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=642, name='Tranquility Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=643, name='Pendulum Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=644, name='Knocking Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=645, name='Salami Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=646, name='Killing Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=647, name='Assault Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=648, name='Roller Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=649, name='Skate Sphere', classification=ItemClassification.filler),
    SingleItemData(item_id=650, name='Symbol of Neutral', classification=ItemClassification.progression),
    SingleItemData(item_id=651, name='Symbol of Heat', classification=ItemClassification.progression),
    SingleItemData(item_id=652, name='Symbol of Cold', classification=ItemClassification.progression),
    SingleItemData(item_id=653, name='Symbol of Shock', classification=ItemClassification.progression),
    SingleItemData(item_id=654, name='Symbol of Wave', classification=ItemClassification.progression),
    SingleItemData(item_id=655, name='Tremor Lab Key', classification=ItemClassification.progression),
    SingleItemData(item_id=656, name='Ultra Secret Note', classification=ItemClassification.filler),
    SingleItemData(item_id=657, name='Sunglass Visor', classification=ItemClassification.useful),
    SingleItemData(item_id=658, name='Lunatic Paws UwU', classification=ItemClassification.useful),
    SingleItemData(item_id=659, name='Meteor Trigger', classification=ItemClassification.useful),
    SingleItemData(item_id=660, name='Asteroid Belt', classification=ItemClassification.useful),
    SingleItemData(item_id=662, name='Asteroid Chunk', classification=ItemClassification.filler),
    SingleItemData(item_id=663, name='Meteor Chunk', classification=ItemClassification.filler),
    SingleItemData(item_id=664, name='Infinity+2 Bag', classification=ItemClassification.useful),
    SingleItemData(item_id=665, name="Lis'mita Cap", classification=ItemClassification.useful),
    SingleItemData(item_id=666, name='Enlightened Halo', classification=ItemClassification.useful),
    SingleItemData(item_id=667, name='Moonwalkers', classification=ItemClassification.useful),
    SingleItemData(item_id=668, name='Moon Chunk', classification=ItemClassification.filler),
    SingleItemData(item_id=669, name='The Last Straw', classification=ItemClassification.filler),
    SingleItemData(item_id=670, name='Goat Cheese', classification=ItemClassification.filler),
    SingleItemData(item_id=671, name='Goat Milk', classification=ItemClassification.filler),
    SingleItemData(item_id=672, name='Manlea', classification=ItemClassification.filler),
    SingleItemData(item_id=673, name='Bearserker Claw', classification=ItemClassification.useful),
    SingleItemData(item_id=674, name='Headset TYPE>:3', classification=ItemClassification.useful),
    SingleItemData(item_id=675, name='Nightfeather Coat', classification=ItemClassification.useful)
]

single_items_dict = {data.name: data for data in single_items_data}

items_by_full_name: dict[str, ItemData] = {}
