# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from BaseClasses import ItemClassification
from .types.Items import ItemData

items_data = [
    ItemData(name='Heat', item_id=0, amount=1, combo_id=300000, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cold', item_id=0, amount=1, combo_id=300001, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Shock', item_id=0, amount=1, combo_id=300002, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Wave', item_id=0, amount=1, combo_id=300003, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Triangle', item_id=0, amount=1, combo_id=300100, classification=ItemClassification.filler, quantity={'linear': 3, 'open': 3}),
    ItemData(name='Masterball', item_id=6, amount=1, combo_id=300106, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Blue Shell', item_id=7, amount=1, combo_id=300107, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Timeworn Belt', item_id=11, amount=1, combo_id=300111, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Humming Razor', item_id=13, amount=1, combo_id=300113, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Dungeon Heart', item_id=18, amount=1, combo_id=300118, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Winterclaw', item_id=38, amount=1, combo_id=300138, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Assault Vest', item_id=48, amount=1, combo_id=300148, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Dented Crown', item_id=54, amount=1, combo_id=300154, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Daikon', item_id=57, amount=1, combo_id=300157, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Copper Gull', item_id=112, amount=1, combo_id=300212, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Rocksplitter', item_id=114, amount=1, combo_id=300214, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cooling Veil', item_id=116, amount=1, combo_id=300216, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Furry Cap', item_id=119, amount=1, combo_id=300219, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Broken Gauntlet', item_id=133, amount=1, combo_id=300233, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Disc of Insight', item_id=135, amount=1, combo_id=300235, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Broken Shield', item_id=137, amount=1, combo_id=300237, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Perforated Tophat', item_id=140, amount=1, combo_id=300240, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Green Leaf Shade', item_id=145, amount=1, combo_id=300245, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Faj'ro Key", item_id=146, amount=1, combo_id=300246, classification=ItemClassification.progression, quantity={'linear': 9, 'open': 9}),
    ItemData(name="Faj'ro Master Key", item_id=147, amount=1, combo_id=300247, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Yellow Sand Shade', item_id=148, amount=1, combo_id=300248, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mine Pass', item_id=149, amount=1, combo_id=300249, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mine Key', item_id=152, amount=1, combo_id=300252, classification=ItemClassification.progression, quantity={'linear': 10, 'open': 10}),
    ItemData(name='Mine Master Key', item_id=153, amount=1, combo_id=300253, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Thief's Key", item_id=154, amount=1, combo_id=300254, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='White Key', item_id=155, amount=1, combo_id=300255, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Radiant Key', item_id=156, amount=1, combo_id=300256, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ancient Sandals', item_id=164, amount=1, combo_id=300264, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Guild Pass', item_id=170, amount=1, combo_id=300270, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Everlasting Amber', item_id=183, amount=1, combo_id=300283, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Epic Metal', item_id=192, amount=1, combo_id=300292, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Laser Eyes', item_id=203, amount=1, combo_id=300303, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Hidden Blade', item_id=221, amount=1, combo_id=300321, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Blue Ice Shade', item_id=225, amount=1, combo_id=300325, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Thief's Band", item_id=228, amount=1, combo_id=300328, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mighty Strand', item_id=229, amount=1, combo_id=300329, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Red Flame Shade', item_id=230, amount=1, combo_id=300330, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Purple Bolt Shade', item_id=231, amount=1, combo_id=300331, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Maroon Cave Pass', item_id=236, amount=1, combo_id=300336, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Galaxy Berry', item_id=261, amount=1, combo_id=300361, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Zir'vitar Key", item_id=272, amount=1, combo_id=300372, classification=ItemClassification.progression, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Disc of Flora', item_id=285, amount=1, combo_id=300385, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Azure Drop Shade', item_id=286, amount=1, combo_id=300386, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Strawhat', item_id=287, amount=1, combo_id=300387, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Aehre', item_id=300, amount=1, combo_id=300400, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sunset Claw', item_id=302, amount=1, combo_id=300402, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sneaky Shiv', item_id=303, amount=1, combo_id=300403, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name="So'najiz Key", item_id=319, amount=1, combo_id=300419, classification=ItemClassification.progression, quantity={'linear': 5, 'open': 5}),
    ItemData(name="King's Ring", item_id=326, amount=1, combo_id=300426, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Burglar's Rope", item_id=329, amount=1, combo_id=300429, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Rough Branch', item_id=332, amount=1, combo_id=300432, classification=ItemClassification.useful, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Bronze Chest Plate', item_id=337, amount=1, combo_id=300437, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Silver Chest Plate', item_id=338, amount=1, combo_id=300438, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Chest Plate', item_id=339, amount=1, combo_id=300439, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Hungry Salmon', item_id=340, amount=1, combo_id=300440, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Pond Slums Pass', item_id=345, amount=1, combo_id=300445, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='One Up', item_id=346, amount=1, combo_id=300446, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Krys'kajo Key", item_id=349, amount=1, combo_id=300449, classification=ItemClassification.progression, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Kajo Master Key', item_id=350, amount=1, combo_id=300450, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Warkeeper', item_id=351, amount=1, combo_id=300451, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Final Dinner', item_id=358, amount=1, combo_id=300458, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Tattered Satchel', item_id=359, amount=1, combo_id=300459, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Green Seed Shade', item_id=376, amount=1, combo_id=300476, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mysterious Box', item_id=380, amount=1, combo_id=300480, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Tremor Engine', item_id=381, amount=1, combo_id=300481, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Dream Globe', item_id=392, amount=1, combo_id=300492, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cursed Coin', item_id=403, amount=1, combo_id=300503, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Broken Sword', item_id=404, amount=1, combo_id=300504, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Star Shade', item_id=410, amount=1, combo_id=300510, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Tengu Mask', item_id=420, amount=1, combo_id=300520, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sonic Spike', item_id=421, amount=1, combo_id=300521, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Lead Boots', item_id=422, amount=1, combo_id=300522, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Omni Lock', item_id=423, amount=1, combo_id=300523, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Shining Bracer', item_id=424, amount=1, combo_id=300524, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Bluefiber Robe', item_id=425, amount=1, combo_id=300525, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Circuit Override', item_id=428, amount=1, combo_id=300528, classification=ItemClassification.progression, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Bright Bracer', item_id=432, amount=1, combo_id=300532, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Meteor Shade', item_id=434, amount=1, combo_id=300534, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Old Dojo Key', item_id=439, amount=1, combo_id=300539, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Broken Deck', item_id=443, amount=1, combo_id=300543, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Heaven's Seed", item_id=447, amount=1, combo_id=300547, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Halcyon Droplet', item_id=454, amount=1, combo_id=300554, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Portrait of Ruin', item_id=455, amount=1, combo_id=300555, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Very Large Ember', item_id=456, amount=1, combo_id=300556, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Moonstone', item_id=460, amount=1, combo_id=300560, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Dried Grass Hat', item_id=467, amount=1, combo_id=300567, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Strawberry Hat', item_id=468, amount=1, combo_id=300568, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Vermillion Mantle', item_id=480, amount=1, combo_id=300580, classification=ItemClassification.useful, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Geta Wood', item_id=484, amount=1, combo_id=300584, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Geta Straps', item_id=485, amount=1, combo_id=300585, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Ticket', item_id=489, amount=1, combo_id=300589, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Old Blueprint', item_id=497, amount=1, combo_id=300597, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Antique Token', item_id=499, amount=1, combo_id=300599, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Broken Chakrams', item_id=515, amount=1, combo_id=300615, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Green Leaf Tea x2', item_id=2, amount=2, combo_id=300778, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chef Sandwich x2', item_id=28, amount=2, combo_id=300804, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mega-Sandwich x2', item_id=40, amount=2, combo_id=300816, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Blazing Bun x2', item_id=66, amount=2, combo_id=300842, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Fruit Pie x2', item_id=72, amount=2, combo_id=300848, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ginger Tom. Salad x2', item_id=78, amount=2, combo_id=300854, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Veggie Set x2', item_id=97, amount=2, combo_id=300873, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Dropped Mic x2', item_id=129, amount=2, combo_id=300905, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Bug Shell x2', item_id=159, amount=2, combo_id=300935, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Blue Orb x2', item_id=160, amount=2, combo_id=300936, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Vanilla Ice Cream x2', item_id=167, amount=2, combo_id=300943, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Rainbow Gem x2', item_id=176, amount=2, combo_id=300952, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Palmapple Seed x2', item_id=178, amount=2, combo_id=300954, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Lucid Shard x2', item_id=182, amount=2, combo_id=300958, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ancient Earth x2', item_id=187, amount=2, combo_id=300963, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Maroon Chestnut x2', item_id=188, amount=2, combo_id=300964, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Refined Metal x2', item_id=190, amount=2, combo_id=300966, classification=ItemClassification.filler, quantity={'linear': 3, 'open': 3}),
    ItemData(name='Precious Metal x2', item_id=191, amount=2, combo_id=300967, classification=ItemClassification.filler, quantity={'linear': 6, 'open': 6}),
    ItemData(name='Epic Metal x2', item_id=192, amount=2, combo_id=300968, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Hardened Liver x2', item_id=198, amount=2, combo_id=300974, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Phoenix Feather x2', item_id=199, amount=2, combo_id=300975, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Magma Residue x2', item_id=202, amount=2, combo_id=300978, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Lazy Claw x2', item_id=278, amount=2, combo_id=301054, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Stout Backplate x2', item_id=279, amount=2, combo_id=301055, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Metal Down x2', item_id=282, amount=2, combo_id=301058, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Plain Cube x2', item_id=283, amount=2, combo_id=301059, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Prime Pistachios x2', item_id=289, amount=2, combo_id=301065, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Energy Espresso x2', item_id=292, amount=2, combo_id=301068, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Full Course x2', item_id=336, amount=2, combo_id=301112, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Just Water x2', item_id=366, amount=2, combo_id=301142, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sharp Splitter x2', item_id=407, amount=2, combo_id=301183, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sticky Web x2', item_id=409, amount=2, combo_id=301185, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Circuit Override x2', item_id=428, amount=2, combo_id=301204, classification=ItemClassification.progression, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ruby x2', item_id=457, amount=2, combo_id=301233, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Diamond x2', item_id=459, amount=2, combo_id=301235, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Topaz x2', item_id=462, amount=2, combo_id=301238, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Emerald x2', item_id=464, amount=2, combo_id=301240, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Bars x2', item_id=488, amount=2, combo_id=301264, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Sandwich x3', item_id=1, amount=3, combo_id=301453, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cross Sandwich x3', item_id=63, amount=3, combo_id=301515, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Flaming Bun x3', item_id=65, amount=3, combo_id=301517, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Veggie Wraps x3', item_id=68, amount=3, combo_id=301520, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Fruit Salad x3', item_id=71, amount=3, combo_id=301523, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Fruit Pie x3', item_id=72, amount=3, combo_id=301524, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Tofu Cracker x3', item_id=74, amount=3, combo_id=301526, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ginger Tom. Salad x3', item_id=78, amount=3, combo_id=301530, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Pepper Night Tea x3', item_id=79, amount=3, combo_id=301531, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chili Dog x3', item_id=87, amount=3, combo_id=301539, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Raw Meat x3', item_id=88, amount=3, combo_id=301540, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Gold Beetle x3', item_id=93, amount=3, combo_id=301545, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Bear Cicada x3', item_id=95, amount=3, combo_id=301547, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Azure Dragonfly x3', item_id=96, amount=3, combo_id=301548, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Winter Thorn x3', item_id=108, amount=3, combo_id=301560, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Dropped Mic x3', item_id=129, amount=3, combo_id=301581, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Echo Roll x3', item_id=132, amount=3, combo_id=301584, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Frosted Carrot x3', item_id=139, amount=3, combo_id=301591, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Bug Shell x3', item_id=159, amount=3, combo_id=301611, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Metal Gears x3', item_id=163, amount=3, combo_id=301615, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sweet Lemonjuice x3', item_id=165, amount=3, combo_id=301617, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Lucid Shard x3', item_id=182, amount=3, combo_id=301634, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ancient Earth x3', item_id=187, amount=3, combo_id=301639, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Refined Metal x3', item_id=190, amount=3, combo_id=301642, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Precious Metal x3', item_id=191, amount=3, combo_id=301643, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Drill Stone x3', item_id=195, amount=3, combo_id=301647, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Squishy Teeth x3', item_id=197, amount=3, combo_id=301649, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Jelly Extract x3', item_id=201, amount=3, combo_id=301653, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Star Fruit x3', item_id=257, amount=3, combo_id=301709, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Lazy Claw x3', item_id=278, amount=3, combo_id=301730, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Stout Backplate x3', item_id=279, amount=3, combo_id=301731, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Living Bolt x3', item_id=281, amount=3, combo_id=301733, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Metal Down x3', item_id=282, amount=3, combo_id=301734, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Plain Cube x3', item_id=283, amount=3, combo_id=301735, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Glow Pear x3', item_id=284, amount=3, combo_id=301736, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Energy Espresso x3', item_id=292, amount=3, combo_id=301744, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sea Disc x3', item_id=314, amount=3, combo_id=301766, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Werewolf Stick x3', item_id=316, amount=3, combo_id=301768, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Green Risotto x3', item_id=357, amount=3, combo_id=301809, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Crystal Water x3', item_id=379, amount=3, combo_id=301831, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Hoverpad x3', item_id=408, amount=3, combo_id=301860, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Geta Glue x3', item_id=486, amount=3, combo_id=301938, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Satchel x3', item_id=487, amount=3, combo_id=301939, classification=ItemClassification.filler, quantity={'linear': 3, 'open': 3}),
    ItemData(name='Golden Bars x3', item_id=488, amount=3, combo_id=301940, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Golden Ticket x3', item_id=489, amount=3, combo_id=301941, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Cheese Spaetzle x3', item_id=491, amount=3, combo_id=301943, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Spicy Beat-0-Type x3', item_id=495, amount=3, combo_id=301947, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Green Leaf Tea x4', item_id=2, amount=4, combo_id=302130, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sweet Berry Tea x4', item_id=3, amount=4, combo_id=302131, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chef Sandwich x4', item_id=28, amount=4, combo_id=302156, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Mega-Sandwich x4', item_id=40, amount=4, combo_id=302168, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cross Sandwich x4', item_id=63, amount=4, combo_id=302191, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Flaming Bun x4', item_id=65, amount=4, combo_id=302193, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Blazing Bun x4', item_id=66, amount=4, combo_id=302194, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Veggie Burger x4', item_id=69, amount=4, combo_id=302197, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Fruit Pie x4', item_id=72, amount=4, combo_id=302200, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cheese Cracker x4', item_id=75, amount=4, combo_id=302203, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Pepper Night Tea x4', item_id=79, amount=4, combo_id=302207, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Metal Needles x4', item_id=81, amount=4, combo_id=302209, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Bovine Skin x4', item_id=82, amount=4, combo_id=302210, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chili Dog x4', item_id=87, amount=4, combo_id=302215, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Raw Meat x4', item_id=88, amount=4, combo_id=302216, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Winter Thorn x4', item_id=108, amount=4, combo_id=302236, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Echo Roll x4', item_id=132, amount=4, combo_id=302260, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Diabolic Horns x4', item_id=141, amount=4, combo_id=302269, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Vanilla Ice Cream x4', item_id=167, amount=4, combo_id=302295, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Arid Lumber x4', item_id=186, amount=4, combo_id=302314, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ancient Earth x4', item_id=187, amount=4, combo_id=302315, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Phoenix Feather x4', item_id=199, amount=4, combo_id=302327, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Butter Silk x4', item_id=200, amount=4, combo_id=302328, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Moon Fruit x4', item_id=260, amount=4, combo_id=302388, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Royal Hive x4', item_id=262, amount=4, combo_id=302390, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Palette Blossom x4', item_id=276, amount=4, combo_id=302404, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Huge Nut x4', item_id=277, amount=4, combo_id=302405, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Power Spinach x4', item_id=280, amount=4, combo_id=302408, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Prime Pistachios x4', item_id=289, amount=4, combo_id=302417, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Salted Peanuts x4', item_id=290, amount=4, combo_id=302418, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Energy Espresso x4', item_id=292, amount=4, combo_id=302420, classification=ItemClassification.filler, quantity={'linear': 3, 'open': 3}),
    ItemData(name='Maultasche x4', item_id=315, amount=4, combo_id=302443, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Werewolf Stick x4', item_id=316, amount=4, combo_id=302444, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Snack Mix x4', item_id=331, amount=4, combo_id=302459, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Full Course x4', item_id=336, amount=4, combo_id=302464, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Wrap Roll x4', item_id=354, amount=4, combo_id=302482, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Shrimp Risotto x4', item_id=356, amount=4, combo_id=302484, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Crystal Water x4', item_id=379, amount=4, combo_id=302507, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Steel Bamboo x4', item_id=388, amount=4, combo_id=302516, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cobalt Crystal x4', item_id=391, amount=4, combo_id=302519, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Elemental DNA x4', item_id=402, amount=4, combo_id=302530, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ronin Shell x4', item_id=405, amount=4, combo_id=302533, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Samurai Shell x4', item_id=406, amount=4, combo_id=302534, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Bars x4', item_id=488, amount=4, combo_id=302616, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Durian x4', item_id=493, amount=4, combo_id=302621, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sandwich x5', item_id=1, amount=5, combo_id=302805, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sweet Berry Tea x5', item_id=3, amount=5, combo_id=302807, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Hi-Sandwich x5', item_id=27, amount=5, combo_id=302831, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chef Sandwich x5', item_id=28, amount=5, combo_id=302832, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Veggie Wraps x5', item_id=68, amount=5, combo_id=302872, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cheese Cracker x5', item_id=75, amount=5, combo_id=302879, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ginger Tom. Salad x5', item_id=78, amount=5, combo_id=302882, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Veggie Set x5', item_id=97, amount=5, combo_id=302901, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Purple Ore Lump x5', item_id=107, amount=5, combo_id=302911, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Echo Roll x5', item_id=132, amount=5, combo_id=302936, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Old Bones x5', item_id=180, amount=5, combo_id=302984, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Refined Metal x5', item_id=190, amount=5, combo_id=302994, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Steel Comb x5', item_id=250, amount=5, combo_id=303054, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Elder Wood x5', item_id=251, amount=5, combo_id=303055, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Virus Root x5', item_id=254, amount=5, combo_id=303058, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Star Fruit x5', item_id=257, amount=5, combo_id=303061, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Slime Drop x5', item_id=275, amount=5, combo_id=303079, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Cold Platter x5', item_id=335, amount=5, combo_id=303139, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Wrap Roll x5', item_id=354, amount=5, combo_id=303158, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Shrimp Risotto x5', item_id=356, amount=5, combo_id=303160, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Mystery Grape x5', item_id=385, amount=5, combo_id=303189, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Infected Cell x5', item_id=401, amount=5, combo_id=303205, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Bars x5', item_id=488, amount=5, combo_id=303292, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chef Sandwich x6', item_id=28, amount=6, combo_id=303508, classification=ItemClassification.filler, quantity={'linear': 4, 'open': 4}),
    ItemData(name='Mega-Sandwich x6', item_id=40, amount=6, combo_id=303520, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Spicy Bun x6', item_id=64, amount=6, combo_id=303544, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Fruit Drink x6', item_id=70, amount=6, combo_id=303550, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Fruit Salad x6', item_id=71, amount=6, combo_id=303551, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Rice Cracker x6', item_id=73, amount=6, combo_id=303553, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Pepper Night Tea x6', item_id=79, amount=6, combo_id=303559, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Headphone Scraps x6', item_id=80, amount=6, combo_id=303560, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Raw Meat x6', item_id=88, amount=6, combo_id=303568, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Twilight Dew x6', item_id=94, amount=6, combo_id=303574, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Rusty Bits x6', item_id=104, amount=6, combo_id=303584, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Pike Wood x6', item_id=106, amount=6, combo_id=303586, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Hotsauce x6', item_id=166, amount=6, combo_id=303646, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Crystal Leek x6', item_id=185, amount=6, combo_id=303665, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Elder Wood x6', item_id=251, amount=6, combo_id=303731, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Spiky Nut x6', item_id=259, amount=6, combo_id=303739, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Static Furball x6', item_id=274, amount=6, combo_id=303754, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Prime Pistachios x6', item_id=289, amount=6, combo_id=303769, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name="Cup o' Coffee x6", item_id=291, amount=6, combo_id=303771, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Snack Mix x6', item_id=331, amount=6, combo_id=303811, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Kebab Roll x6', item_id=353, amount=6, combo_id=303833, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Just Water x6', item_id=366, amount=6, combo_id=303846, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sticky Web x6', item_id=409, amount=6, combo_id=303889, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Golden Satchel x6', item_id=487, amount=6, combo_id=303967, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Golden Bars x6', item_id=488, amount=6, combo_id=303968, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sweet Berry Tea x7', item_id=3, amount=7, combo_id=304159, classification=ItemClassification.filler, quantity={'linear': 2, 'open': 2}),
    ItemData(name='Fruit Salad x7', item_id=71, amount=7, combo_id=304227, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sweet Lemonjuice x7', item_id=165, amount=7, combo_id=304321, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Glaring Rock x7', item_id=175, amount=7, combo_id=304331, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Vivid Water x7', item_id=177, amount=7, combo_id=304333, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Ripe Apples x7', item_id=242, amount=7, combo_id=304398, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Wolf Cicada x7', item_id=245, amount=7, combo_id=304401, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Crimson Dragonfly x7', item_id=246, amount=7, combo_id=304402, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Glowing Sphere x7', item_id=253, amount=7, combo_id=304409, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Salted Peanuts x7', item_id=290, amount=7, combo_id=304446, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Chef Sandwich x8', item_id=28, amount=8, combo_id=304860, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Sunset Dew x8', item_id=244, amount=8, combo_id=305076, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Common Planter x8', item_id=258, amount=8, combo_id=305090, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Catalop Pellet x8', item_id=387, amount=8, combo_id=305219, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Spark Tin x8', item_id=390, amount=8, combo_id=305222, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1}),
    ItemData(name='Venom Shroom x9', item_id=252, amount=9, combo_id=305760, classification=ItemClassification.filler, quantity={'linear': 1, 'open': 1})
]

items_dict = {data.name: data for data in items_data}