from typing import NamedTuple
from BaseClasses import Location

class CrossCodeLocation(Location):
    game: str = "CrossCode"

    def __init__(self, player: int, name = "", code = None, parent = None):
        super(CrossCodeLocation, self).__init__(player, name, code, parent)
        self.event = code is None

class LocationData(NamedTuple):
    name: str
    offset: int
    clearance: str
    region: str

locations_data = [
	LocationData(name='Vermillion Wasteland - Spiral Cliff - Bronze Chest', offset=0, clearance='Bronze', region='22'),
	LocationData(name='Vermillion Wasteland - Spiral Cliff - Chest', offset=1, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - Storage Basement - Chest', offset=2, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - Crimson Lake - Chest 1', offset=3, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - Crimson Lake - Chest 2', offset=4, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - East Town - Silver Chest', offset=5, clearance='Silver', region='22'),
	LocationData(name='Vermillion Wasteland - East Town - Chest 1', offset=6, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - East Town - Chest 2', offset=7, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - West Town - Bronze Chest 1', offset=8, clearance='Bronze', region='22'),
	LocationData(name='Vermillion Wasteland - West Town - Chest', offset=9, clearance='Default', region='22'),
	LocationData(name='Vermillion Wasteland - West Town - Bronze Chest 2', offset=10, clearance='Bronze', region='22'),
	LocationData(name="Autumn's Rise - Drippy Den - Chest", offset=11, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Normal Clearing - Chest 1", offset=12, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Normal Clearing - Chest 2", offset=13, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Entrance - Chest", offset=14, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Old Observatory - Chest", offset=15, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Quiet Passage 1 - Chest", offset=16, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Quiet Passage 2 - Chest", offset=17, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Hedgehag's Den - Chest", offset=18, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 1 - Chest", offset=19, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 2 - Chest", offset=20, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 3 - Chest", offset=21, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Off Road 1 - Chest", offset=22, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Off Road 2 - Chest", offset=23, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 6 - Chest 1", offset=24, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 6 - Chest 2", offset=25, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 6 - Chest 3", offset=26, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 7 - Chest 1", offset=27, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 7 - Chest 2", offset=28, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Ending Pathway - Chest", offset=29, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Obelisk Lake - Bronze Chest", offset=30, clearance='Bronze', region='3'),
	LocationData(name="Autumn's Rise - Obelisk Lake - Chest", offset=31, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 4 - Chest 1", offset=32, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 4 - Chest 2", offset=33, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 4 - Chest 3", offset=34, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 5 - Chest 1", offset=35, clearance='Default', region='3'),
	LocationData(name="Autumn's Rise - Pathway 5 - Chest 2", offset=36, clearance='Default', region='3'),
	LocationData(name="Autumn's Fall - Ruby Tunnel - Gold Chest", offset=37, clearance='Gold', region='31'),
	LocationData(name="Autumn's Fall - Lake Cave 1 - Chest", offset=38, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Lake Cave 2 - Chest", offset=39, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Lake Cave 3 - Silver Chest", offset=40, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Lake Cave 4 - Chest", offset=41, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Southern Exit - Chest 1", offset=42, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Southern Exit - Chest 2", offset=43, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Southern Exit - Chest 3", offset=44, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Ruined Path - Chest", offset=45, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Ruined Path - Gold Chest", offset=46, clearance='Gold', region='20'),
	LocationData(name="Autumn's Fall - Eastern Exit - Silver Chest", offset=47, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Eastern Exit - Chest", offset=48, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Ancient Center - Silver Chest 1", offset=49, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Ancient Center - Silver Chest 2", offset=50, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Northern Exit - Chest", offset=51, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Northern Exit - Bronze Chest", offset=52, clearance='Bronze', region='20'),
	LocationData(name="Autumn's Fall - Pillar Isle - Chest 1", offset=53, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Pillar Isle - Chest 2", offset=54, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Pillar Isle - Chest 3", offset=55, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Village Remains - Silver Chest", offset=56, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Village Remains - Gold Chest", offset=57, clearance='Gold', region='20'),
	LocationData(name="Autumn's Fall - Village Remains - Bronze Chest", offset=58, clearance='Bronze', region='20'),
	LocationData(name="Autumn's Fall - Secluded Path - Gold Chest", offset=59, clearance='Gold', region='20'),
	LocationData(name="Autumn's Fall - Secluded Path - Chest 1", offset=60, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Secluded Path - Chest 2", offset=61, clearance='Default', region='20'),
	LocationData(name="Autumn's Fall - Villa of Terror - Silver Chest", offset=62, clearance='Silver', region='20'),
	LocationData(name="Autumn's Fall - Villa of Terror - Bronze Chest", offset=63, clearance='Bronze', region='20'),
	LocationData(name="Autumn's Fall - Para Island 1 - Chest", offset=64, clearance='Default', region='21'),
	LocationData(name='Bergen Village - Bergen South - Chest', offset=65, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Bergen South - Bronze Chest 1', offset=66, clearance='Bronze', region='3'),
	LocationData(name='Bergen Village - Bergen South - Bronze Chest 2', offset=67, clearance='Bronze', region='3'),
	LocationData(name='Bergen Village - Bergen South - Gold Chest', offset=68, clearance='Gold', region='3'),
	LocationData(name='Bergen Village - Bergen North - Chest 1', offset=69, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Bergen North - Chest 2', offset=70, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Bergen North - Silver Chest', offset=71, clearance='Silver', region='3'),
	LocationData(name='Bergen Village - Bergen North - Chest 3', offset=72, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Diving Railway - Chest', offset=73, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Seeker Hub Cellar - Chest', offset=74, clearance='Default', region='3'),
	LocationData(name='Bergen Village - Seeker Hub Cellar - Bronze Chest', offset=75, clearance='Bronze', region='3'),
	LocationData(name='Bergen Village - Storage Room - Chest', offset=76, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Abandoned Cave  - Chest', offset=77, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Frozen Cave - Chest', offset=78, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Abandoned Ground - Silver Chest', offset=79, clearance='Silver', region='3'),
	LocationData(name="Bergen Trail - Pengpeng's Den - Chest", offset=80, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Entrance - Chest 1', offset=81, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Entrance - Chest 2', offset=82, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 1 - Chest', offset=83, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 1 - Chest 1', offset=84, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 1 - Chest 2', offset=85, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 2 - Chest 1', offset=86, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 2 - Chest 2', offset=87, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 2 - Chest 3', offset=88, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 3 - Chest 1', offset=89, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Off Road 3 - Chest 2', offset=90, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Old Plateau - Gold Chest', offset=91, clearance='Gold', region='3'),
	LocationData(name='Bergen Trail - Rising Path 2 - Chest', offset=92, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 3 - Chest 1', offset=93, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 3 - Chest 2', offset=94, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Spike Heights - Chest', offset=95, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Spike Heights - Bronze Chest', offset=96, clearance='Bronze', region='3'),
	LocationData(name='Bergen Trail - Icy Cauldron - Silver Chest', offset=97, clearance='Silver', region='3'),
	LocationData(name='Bergen Trail - Bergen Waterfalls - Chest', offset=98, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 4 - Chest 1', offset=99, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 4 - Chest 2', offset=100, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Lofty Heights - Bronze Chest', offset=101, clearance='Bronze', region='3'),
	LocationData(name='Bergen Trail - Windy Climb - Chest', offset=102, clearance='Default', region='3'),
	LocationData(name='Bergen Trail - Rising Path 5 - Chest', offset=103, clearance='Default', region='3'),
	LocationData(name='Temple Mine - Elevator - Chest', offset=104, clearance='Default', region='5'),
	LocationData(name='Temple Mine - Crossing Funnel - Chest', offset=105, clearance='Default', region='5'),
	LocationData(name='Temple Mine - Old Shaft 1 - Chest', offset=106, clearance='Default', region='5'),
	LocationData(name='Temple Mine - Old Shaft 2 - Chest', offset=107, clearance='Default', region='5'),
	LocationData(name='Temple Mine - Testing Chamber - Chest', offset=108, clearance='Default', region='5'),
	LocationData(name='Temple Mine - Old Chamber - Chest', offset=109, clearance='Default', region='6'),
	LocationData(name='Temple Mine - Storage Room 1 - Bronze Chest', offset=110, clearance='Bronze', region='7'),
	LocationData(name='Temple Mine - Frozen Chamber 1 - Chest', offset=111, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Frozen Chamber 2 - Bronze Chest 1', offset=112, clearance='Bronze', region='9'),
	LocationData(name='Temple Mine - Frozen Chamber 2 - Bronze Chest 2', offset=113, clearance='Bronze', region='9'),
	LocationData(name='Temple Mine - Frozen Shaft 1 - Chest', offset=114, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Frozen Shaft 2 - Chest', offset=115, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Frozen Shaft 3 - Chest', offset=116, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Frozen Shaft 3 - Bronze Chest', offset=117, clearance='Bronze', region='7'),
	LocationData(name='Temple Mine - Overrun Chamber - Chest 1', offset=118, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Overrun Chamber - Chest 2', offset=119, clearance='Default', region='7'),
	LocationData(name='Temple Mine - Elevator - Chest', offset=120, clearance='Default', region='9'),
	LocationData(name='Temple Mine - Infested Chamber - Chest', offset=121, clearance='Default', region='10'),
	LocationData(name='Temple Mine - Forgotten Shaft 1 - Chest', offset=122, clearance='Default', region='9'),
	LocationData(name='Temple Mine - Forgotten Shaft 2 - Bronze Chest', offset=123, clearance='Bronze', region='9'),
	LocationData(name='Temple Mine - Forgotten Shaft 3 - Chest', offset=124, clearance='Default', region='9'),
	LocationData(name='Temple Mine - Forgotten Shaft 4 - Chest', offset=125, clearance='Default', region='9'),
	LocationData(name='Temple Mine - Forgotten Shaft 5 - Chest', offset=126, clearance='Default', region='9'),
	LocationData(name='Temple Mine - Elevator - Bronze Chest', offset=127, clearance='Bronze', region='4'),
	LocationData(name='Temple Mine - Temple Chamber 2 - Chest', offset=128, clearance='Default', region='4'),
	LocationData(name='Sapphire Ridge - The Barracks - Bronze Chest', offset=129, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - The Bellow - Gold Chest', offset=130, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Sapphire Tunnel - Gold Chest', offset=131, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Eroded Passage - Silver Chest', offset=132, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Eroded Passage - Chest', offset=133, clearance='Default', region='31'),
	LocationData(name='Sapphire Ridge - Spider Chasm - Bronze Chest', offset=134, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - Spider Chasm - Gold Chest', offset=135, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Narrow Passage - Silver Chest', offset=136, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Narrow Passage - Bronze Chest', offset=137, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - Wheel Passage - Gold Chest', offset=138, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Wheel Passage - Bronze Chest', offset=139, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - Cave Inn 1F - Chest', offset=140, clearance='Default', region='31'),
	LocationData(name='Sapphire Ridge - Cave Inn Storage - Gold Chest', offset=141, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Western Exit - Chest', offset=142, clearance='Default', region='31'),
	LocationData(name='Sapphire Ridge - Western Exit - Bronze Chest', offset=143, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - North West Path - Silver Chest', offset=144, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - North West Path - Bronze Chest', offset=145, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - River Road - Bronze Chest 1', offset=146, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - River Road - Gold Chest', offset=147, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - River Road - Bronze Chest 2', offset=148, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - The Cave Inn - Bronze Chest', offset=149, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - The Cave Inn - Gold Chest', offset=150, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Tranquil Bamboo - Bronze Chest', offset=151, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - Tranquil Bamboo - Chest', offset=152, clearance='Default', region='31'),
	LocationData(name='Sapphire Ridge - Bamboo Thicket - Silver Chest', offset=153, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Bamboo Thicket - Gold Chest', offset=154, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - North East Path - Silver Chest', offset=155, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - North East Path - Gold Chest', offset=156, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Flower Lake - Gold Chest 1', offset=157, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Flower Lake - Gold Chest 2', offset=158, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Carved Pathway - Gold Chest', offset=159, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Carved Pathway - Silver Chest', offset=160, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Carved Pathway - Bronze Chest', offset=161, clearance='Bronze', region='31'),
	LocationData(name='Sapphire Ridge - High Ground - Gold Chest', offset=162, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - High Ground - Silver Chest', offset=163, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Old Dojo - Silver Chest', offset=164, clearance='Silver', region='31'),
	LocationData(name='Sapphire Ridge - Old Dojo - Gold Chest 1', offset=165, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Old Dojo - Gold Chest 2', offset=166, clearance='Gold', region='31'),
	LocationData(name='Sapphire Ridge - Dream Pond - Gold Chest', offset=167, clearance='Gold', region='33'),
	LocationData(name='Sapphire Ridge - Ascension Temple - Gold Chest', offset=168, clearance='Gold', region='33'),
	LocationData(name='Sapphire Ridge - Ascension Temple - Silver Chest 1', offset=169, clearance='Silver', region='33'),
	LocationData(name='Sapphire Ridge - Ascension Temple - Silver Chest 2', offset=170, clearance='Silver', region='33'),
	LocationData(name='Sapphire Ridge - Baton Pond - Bronze Chest', offset=171, clearance='Bronze', region='31'),
	LocationData(name='Maroon Valley - Mystery Cave - Gold Chest', offset=172, clearance='Gold', region='11'),
	LocationData(name='Maroon Valley - Mystery Cave - Silver Chest', offset=173, clearance='Silver', region='11'),
	LocationData(name='Maroon Valley - Maroon Cave 1 - Chest', offset=174, clearance='Default', region='12'),
	LocationData(name='Maroon Valley - River Cliff - Chest 1', offset=175, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - River Cliff - Chest 2', offset=176, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Endless Pit - Chest 1', offset=177, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Endless Pit - Chest 2', offset=178, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Endless Pit - Chest 3', offset=179, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Vivid Path - Chest 1', offset=180, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Vivid Path - Chest 2', offset=181, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Maroon Oasis - Chest 1', offset=182, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Maroon Oasis - Chest 2', offset=183, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Bright Path - Bronze Chest', offset=184, clearance='Bronze', region='11'),
	LocationData(name='Maroon Valley - Rising Railway - Chest', offset=185, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - East Entrance - Chest', offset=186, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Dusty Path - Bronze Chest', offset=187, clearance='Bronze', region='11'),
	LocationData(name='Maroon Valley - Dusty Path - Chest', offset=188, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Crossroad - Chest 1', offset=189, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Crossroad - Chest 2', offset=190, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Long Piece - Chest', offset=191, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Barren Arcs - Chest', offset=192, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Barren Arcs - Bronze Chest', offset=193, clearance='Bronze', region='11'),
	LocationData(name='Maroon Valley - Barren Land - Chest', offset=194, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Overpass - Chest 1', offset=195, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Overpass - Chest 2', offset=196, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Paw Cliffs - Chest', offset=197, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Paw Cliffs - Silver Chest', offset=198, clearance='Silver', region='11'),
	LocationData(name='Maroon Valley - Torn Road - Chest 1', offset=199, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Torn Road - Chest 2', offset=200, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - West Entrance - Chest', offset=201, clearance='Default', region='11'),
	LocationData(name='Maroon Valley - Fractured Path - Silver Chest', offset=202, clearance='Silver', region='11'),
	LocationData(name='Maroon Valley - Fractured Path - Chest', offset=203, clearance='Default', region='11'),
	LocationData(name="Faj'ro Temple - Right Chamber 1 - Chest", offset=204, clearance='Default', region='15'),
	LocationData(name="Faj'ro Temple - Bottom Chamber - Chest", offset=205, clearance='Default', region='17'),
	LocationData(name="Faj'ro Temple - Large Fire Chamber - Bronze Chest", offset=206, clearance='Bronze', region='17.5'),
	LocationData(name="Faj'ro Temple - Large Fire Chamber - Silver Chest", offset=207, clearance='Silver', region='17.5'),
	LocationData(name="Faj'ro Temple - Test of Wisdom - Chest", offset=208, clearance='Default', region='17.5'),
	LocationData(name="Faj'ro Temple - West Pathway - Chest", offset=209, clearance='Default', region='17'),
	LocationData(name="Faj'ro Temple - Test of Surprise - Chest", offset=210, clearance='Default', region='17'),
	LocationData(name="Faj'ro Temple - West Chamber 1 - Chest", offset=211, clearance='Default', region='17.5'),
	LocationData(name="Faj'ro Temple - East Chamber 1 - Chest", offset=212, clearance='Default', region='17.5'),
	LocationData(name="Faj'ro Temple - East Pathway - Silver Chest", offset=213, clearance='Silver', region='17'),
	LocationData(name="Faj'ro Temple - Test of Memory - Chest", offset=214, clearance='Default', region='17.5'),
	LocationData(name="Faj'ro Temple - Chamber of Prosperity - Chest", offset=215, clearance='Default', region='18'),
	LocationData(name="Faj'ro Temple - Left Chamber 1 - Chest", offset=216, clearance='Default', region='13'),
	LocationData(name="Faj'ro Temple - Fire and Sand 2 - Chest", offset=217, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Balance Room 2 - Chest 1", offset=218, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Balance Room 2 - Chest 2", offset=219, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Right Chamber 1 - Chest", offset=220, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Right Chamber 2 - Chest", offset=221, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Test of Memory 1 - Chest", offset=222, clearance='Default', region='14'),
	LocationData(name="Faj'ro Temple - Test of Memory 2 - Chest", offset=223, clearance='Default', region='14'),
	LocationData(name="Ba'kii Kum - Solar Farm - Chest 1", offset=224, clearance='Default', region='11'),
	LocationData(name="Ba'kii Kum - Solar Farm - Chest 2", offset=225, clearance='Default', region='11'),
	LocationData(name="Ba'kii Kum - Market - Chest", offset=226, clearance='Default', region='11'),
	LocationData(name="Ba'kii Kum - Market - Bronze Chest", offset=227, clearance='Bronze', region='11'),
	LocationData(name="Ba'kii Kum - Bazaar House - Silver Chest", offset=228, clearance='Silver', region='11'),
	LocationData(name="Gaia's Garden - Dripping Cave - Silver Chest", offset=229, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Tranquility Pond - Gold Chest", offset=230, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil West - Gold Chest", offset=231, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil West - Silver Chest", offset=232, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil West - Bronze Chest", offset=233, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil East - Bronze Chest", offset=234, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil East - Silver Chest", offset=235, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil North - Gold Chest", offset=236, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - V'rda Vil North - Silver Chest", offset=237, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Chief's Den - Silver Chest", offset=238, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Chief's Den - Bronze Chest", offset=239, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - Chief's Den - Gold Chest", offset=240, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - Grand Krys'kajo Entrance - Bronze Chest", offset=241, clearance='Bronze', region='28'),
	LocationData(name="Gaia's Garden - So'najiz Temple Entrance - Silver Chest", offset=242, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Covert Path - Chest 1", offset=243, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Covert Path - Chest 2", offset=244, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Royal Grove - Silver Chest", offset=245, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Royal Grove - Chest 1", offset=246, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Royal Grove - Chest 2", offset=247, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Royal Grove - Chest 3", offset=248, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Calm Backyard - Chest 1", offset=249, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Calm Backyard - Chest 2", offset=250, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Lost Lookout - Chest 1", offset=251, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Lost Lookout - Chest 2", offset=252, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Lost Lookout - Chest 3", offset=253, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Seared Lake - Chest 1", offset=254, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Seared Lake - Chest 2", offset=255, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes South - Chest 1", offset=256, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes South - Chest 2", offset=257, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes South - Chest 3", offset=258, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes South - Chest 4", offset=259, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes North - Chest 1", offset=260, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes North - Chest 2", offset=261, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes North - Silver Chest 1", offset=262, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Infested Marshes North - Silver Chest 2", offset=263, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Overgrown Path - Bronze Chest 1", offset=264, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - Overgrown Path - Bronze Chest 2", offset=265, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - Drizzle Bosk - Gold Chest", offset=266, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - Drizzle Bosk - Chest 1", offset=267, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Drizzle Bosk - Chest 2", offset=268, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Wet Passage - Bronze Chest", offset=269, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - Wet Passage - Chest", offset=270, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - River's Bed - Silver Chest", offset=271, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - River's Bed - Chest", offset=272, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Jungle Entrance - Chest 1", offset=273, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Jungle Entrance - Chest 2", offset=274, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Crossroad - Gold Chest", offset=275, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - Crossroad - Chest", offset=276, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Tying Greens - Chest 1", offset=277, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Tying Greens - Chest 2", offset=278, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Peridot Approach - Silver Chest", offset=279, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Peridot Approach - Chest", offset=280, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Splitting Stumps - Chest 1", offset=281, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Splitting Stumps - Chest 2", offset=282, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Clinging River - Silver Chest", offset=283, clearance='Silver', region='23'),
	LocationData(name="Gaia's Garden - Clinging River - Gold Chest", offset=284, clearance='Gold', region='23'),
	LocationData(name="Gaia's Garden - Ringing River - Bronze Chest", offset=285, clearance='Bronze', region='23'),
	LocationData(name="Gaia's Garden - Ringing River - Chest", offset=286, clearance='Default', region='23'),
	LocationData(name="Gaia's Garden - Old Timber - Chest", offset=287, clearance='Default', region='23'),
	LocationData(name='Basin Keep - Centrum - Gold Chest', offset=288, clearance='Gold', region='24'),
	LocationData(name='Basin Keep - Pond Slums - Silver Chest 1', offset=289, clearance='Silver', region='24'),
	LocationData(name='Basin Keep - Pond Slums - Silver Chest 2', offset=290, clearance='Silver', region='24'),
	LocationData(name='Basin Keep - Pond Slums - Gold Chest', offset=291, clearance='Gold', region='24'),
	LocationData(name="Gaia's Garden - Basin Keep Entrance - Chest", offset=292, clearance='Default', region='23'),
	LocationData(name='Basin Keep - Basin Police Force HQ - Gold Chest', offset=293, clearance='Gold', region='23'),
	LocationData(name='Basin Keep - Seeker Hub 1st Floor - Silver Chest', offset=294, clearance='Silver', region='23'),
	LocationData(name='Rhombus Dungeon - Ability Room 1 - Chest 1', offset=295, clearance='Default', region='1'),
	LocationData(name='Rhombus Dungeon - Ability Room 1 - Chest 2', offset=296, clearance='Default', region='1'),
	LocationData(name='Rhombus Square - Arena Plaza - Bronze Chest', offset=297, clearance='Bronze', region='33'),
	LocationData(name='Rhombus Square - Arena Plaza - Silver Chest', offset=298, clearance='Silver', region='33'),
	LocationData(name='Rhombus Square - Garden Boulevard - Bronze Chest', offset=299, clearance='Bronze', region='33'),
	LocationData(name='Rhombus Square - Garden Boulevard - Silver Chest', offset=300, clearance='Silver', region='33'),
	LocationData(name='Rhombus Square - South Arch - Gold Chest', offset=301, clearance='Gold', region='33'),
	LocationData(name='Rhombus Square - Lloyd Passage - Silver Chest', offset=302, clearance='Silver', region='33'),
	LocationData(name='Rookie Harbor - Marketplace - Chest', offset=303, clearance='Default', region='2'),
	LocationData(name='Rookie Harbor - Falling Exit - Chest', offset=304, clearance='Default', region='2'),
	LocationData(name='Rookie Harbor - Weapon & Backer Shop - Silver Chest', offset=305, clearance='Silver', region='19'),
	LocationData(name='Rookie Harbor - Dusty Storage - Silver Chest', offset=306, clearance='Silver', region='19'),
	LocationData(name='Rookie Harbor - South Harbor - Gold Chest', offset=307, clearance='Gold', region='2'),
	LocationData(name='Rookie Harbor - Beginners Arc - Chest 1', offset=308, clearance='Default', region='2'),
	LocationData(name='Rookie Harbor - Beginners Arc - Chest 2', offset=309, clearance='Default', region='2'),
	LocationData(name="Zir'vitar Temple - Moving Transmit - Chest 1", offset=310, clearance='Default', region='23'),
	LocationData(name="Zir'vitar Temple - Moving Transmit - Chest 2", offset=311, clearance='Default', region='25'),
	LocationData(name="Zir'vitar Temple - Haunted Waves - Bronze Chest", offset=312, clearance='Bronze', region='25'),
	LocationData(name="Zir'vitar Temple - Hoodwink - Chest", offset=313, clearance='Default', region='23'),
	LocationData(name="Zir'vitar Temple - Spinning Transmit - Bronze Chest", offset=314, clearance='Bronze', region='25'),
	LocationData(name="Grand Krys'kajo - East Branch - Gold Chest", offset=315, clearance='Gold', region='28'),
	LocationData(name="Grand Krys'kajo - East Branch - Chest 1", offset=316, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - East Branch - Chest 2", offset=317, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - West Branch - Chest 1", offset=318, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - West Branch - Chest 2", offset=319, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - Falling Leaves - MasterKey Chest", offset=320, clearance='MasterKey', region='29'),
	LocationData(name="Grand Krys'kajo - Branch Conveyance - Chest", offset=321, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - Branch Transmit - Chest 1", offset=322, clearance='Default', region='28'),
	LocationData(name="Grand Krys'kajo - Branch Transmit - Chest 2", offset=323, clearance='Default', region='28'),
	LocationData(name="So'najiz Temple - Principle of Conveyance - Chest", offset=324, clearance='Default', region='23'),
	LocationData(name="So'najiz Temple - Trial of Persistence - Chest 1", offset=325, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Trial of Persistence - Chest 2", offset=326, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Trial of Persistence - Chest 3", offset=327, clearance='Default', region='23'),
	LocationData(name="So'najiz Temple - Trial of Persistence - Silver Chest", offset=328, clearance='Silver', region='26'),
	LocationData(name="So'najiz Temple - Trial of Persistence - Gold Chest", offset=329, clearance='Gold', region='26'),
	LocationData(name="So'najiz Temple - Moving Attraction - Chest", offset=330, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Slowing Attraction - Chest", offset=331, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Standing Attraction - Chest", offset=332, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Attracting Conveyance - Chest", offset=333, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Fast Conveyance - Chest", offset=334, clearance='Default', region='26'),
	LocationData(name="So'najiz Temple - Flaming Conveyance - Chest", offset=335, clearance='Default', region='26')
]