# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from .types.Locations import LocationData
from .types.Condition import *

locations_data = [
    LocationData(code=300000, name='Vermillion Wasteland - Spiral Cliff - Bronze Chest'),
    LocationData(code=300001, name='Vermillion Wasteland - Spiral Cliff - Chest'),
    LocationData(code=300002, name='Vermillion Wasteland - Storage Basement - Chest'),
    LocationData(code=300003, name='Vermillion Wasteland - Crimson Lake - Chest 1'),
    LocationData(code=300004, name='Vermillion Wasteland - Crimson Lake - Chest 2'),
    LocationData(code=300005, name='Vermillion Wasteland - East Town - Silver Chest'),
    LocationData(code=300006, name='Vermillion Wasteland - East Town - Chest 1'),
    LocationData(code=300007, name='Vermillion Wasteland - East Town - Chest 2'),
    LocationData(code=300008, name='Vermillion Wasteland - West Town - Bronze Chest 1'),
    LocationData(code=300009, name='Vermillion Wasteland - West Town - Chest'),
    LocationData(code=300010, name='Vermillion Wasteland - West Town - Bronze Chest 2'),
    LocationData(code=300011, name="Autumn's Rise - Drippy Den - Chest"),
    LocationData(code=300012, name="Autumn's Rise - Normal Clearing - Chest 1"),
    LocationData(code=300013, name="Autumn's Rise - Normal Clearing - Chest 2"),
    LocationData(code=300014, name="Autumn's Rise - Entrance - Chest"),
    LocationData(code=300015, name="Autumn's Rise - Old Observatory - Chest"),
    LocationData(code=300016, name="Autumn's Rise - Quiet Passage 1 - Chest"),
    LocationData(code=300017, name="Autumn's Rise - Quiet Passage 2 - Chest"),
    LocationData(code=300018, name="Autumn's Rise - Hedgehag's Den - Chest"),
    LocationData(code=300019, name="Autumn's Rise - Pathway 1 - Chest"),
    LocationData(code=300020, name="Autumn's Rise - Pathway 2 - Chest"),
    LocationData(code=300021, name="Autumn's Rise - Pathway 3 - Chest"),
    LocationData(code=300022, name="Autumn's Rise - Off Road 1 - Chest"),
    LocationData(code=300023, name="Autumn's Rise - Off Road 2 - Chest"),
    LocationData(code=300024, name="Autumn's Rise - Pathway 6 - Chest 1"),
    LocationData(code=300025, name="Autumn's Rise - Pathway 6 - Chest 2"),
    LocationData(code=300026, name="Autumn's Rise - Pathway 6 - Chest 3"),
    LocationData(code=300027, name="Autumn's Rise - Pathway 7 - Chest 1"),
    LocationData(code=300028, name="Autumn's Rise - Pathway 7 - Chest 2"),
    LocationData(code=300029, name="Autumn's Rise - Ending Pathway - Chest"),
    LocationData(code=300030, name="Autumn's Rise - Obelisk Lake - Bronze Chest"),
    LocationData(code=300031, name="Autumn's Rise - Obelisk Lake - Chest"),
    LocationData(code=300032, name="Autumn's Rise - Pathway 4 - Chest 1"),
    LocationData(code=300033, name="Autumn's Rise - Pathway 4 - Chest 2"),
    LocationData(code=300034, name="Autumn's Rise - Pathway 4 - Chest 3"),
    LocationData(code=300035, name="Autumn's Rise - Pathway 5 - Chest 1"),
    LocationData(code=300036, name="Autumn's Rise - Pathway 5 - Chest 2"),
    LocationData(code=300037, name="Autumn's Fall - Ruby Tunnel - Gold Chest"),
    LocationData(code=300038, name="Autumn's Fall - Lake Cave 1 - Chest"),
    LocationData(code=300039, name="Autumn's Fall - Lake Cave 2 - Chest"),
    LocationData(code=300040, name="Autumn's Fall - Lake Cave 3 - Silver Chest"),
    LocationData(code=300041, name="Autumn's Fall - Lake Cave 4 - Chest"),
    LocationData(code=300042, name="Autumn's Fall - Southern Exit - Chest 1"),
    LocationData(code=300043, name="Autumn's Fall - Southern Exit - Chest 2"),
    LocationData(code=300044, name="Autumn's Fall - Southern Exit - Chest 3"),
    LocationData(code=300045, name="Autumn's Fall - Ruined Path - Chest"),
    LocationData(code=300046, name="Autumn's Fall - Ruined Path - Gold Chest"),
    LocationData(code=300047, name="Autumn's Fall - Eastern Exit - Silver Chest"),
    LocationData(code=300048, name="Autumn's Fall - Eastern Exit - Chest"),
    LocationData(code=300049, name="Autumn's Fall - Ancient Center - Silver Chest 1"),
    LocationData(code=300050, name="Autumn's Fall - Ancient Center - Silver Chest 2"),
    LocationData(code=300051, name="Autumn's Fall - Northern Exit - Chest"),
    LocationData(code=300052, name="Autumn's Fall - Northern Exit - Bronze Chest"),
    LocationData(code=300053, name="Autumn's Fall - Pillar Isle - Chest 1"),
    LocationData(code=300054, name="Autumn's Fall - Pillar Isle - Chest 2"),
    LocationData(code=300055, name="Autumn's Fall - Pillar Isle - Chest 3"),
    LocationData(code=300056, name="Autumn's Fall - Village Remains - Silver Chest"),
    LocationData(code=300057, name="Autumn's Fall - Village Remains - Gold Chest"),
    LocationData(code=300058, name="Autumn's Fall - Village Remains - Bronze Chest"),
    LocationData(code=300059, name="Autumn's Fall - Secluded Path - Gold Chest"),
    LocationData(code=300060, name="Autumn's Fall - Secluded Path - Chest 1"),
    LocationData(code=300061, name="Autumn's Fall - Secluded Path - Chest 2"),
    LocationData(code=300062, name="Autumn's Fall - Villa of Terror - Silver Chest"),
    LocationData(code=300063, name="Autumn's Fall - Villa of Terror - Bronze Chest"),
    LocationData(code=300064, name="Autumn's Fall - Para Island 1 - Chest"),
    LocationData(code=300065, name='Bergen Village - Bergen South - Chest'),
    LocationData(code=300066, name='Bergen Village - Bergen South - Bronze Chest 1'),
    LocationData(code=300067, name='Bergen Village - Bergen South - Bronze Chest 2'),
    LocationData(code=300068, name='Bergen Village - Bergen South - Gold Chest'),
    LocationData(code=300069, name='Bergen Village - Bergen North - Chest 1'),
    LocationData(code=300070, name='Bergen Village - Bergen North - Chest 2'),
    LocationData(code=300071, name='Bergen Village - Bergen North - Silver Chest'),
    LocationData(code=300072, name='Bergen Village - Bergen North - Chest 3'),
    LocationData(code=300073, name='Bergen Village - Diving Railway - Chest'),
    LocationData(code=300074, name='Bergen Village - Seeker Hub Cellar - Chest'),
    LocationData(code=300075, name='Bergen Village - Seeker Hub Cellar - Bronze Chest'),
    LocationData(code=300076, name='Bergen Village - Storage Room - Chest'),
    LocationData(code=300077, name='Bergen Trail - Abandoned Cave  - Chest'),
    LocationData(code=300078, name='Bergen Trail - Frozen Cave - Chest'),
    LocationData(code=300079, name='Bergen Trail - Abandoned Ground - Silver Chest'),
    LocationData(code=300080, name="Bergen Trail - Pengpeng's Den - Chest"),
    LocationData(code=300081, name='Bergen Trail - Entrance - Chest 1'),
    LocationData(code=300082, name='Bergen Trail - Entrance - Chest 2'),
    LocationData(code=300083, name='Bergen Trail - Rising Path 1 - Chest'),
    LocationData(code=300084, name='Bergen Trail - Off Road 1 - Chest 1'),
    LocationData(code=300085, name='Bergen Trail - Off Road 1 - Chest 2'),
    LocationData(code=300086, name='Bergen Trail - Off Road 2 - Chest 1'),
    LocationData(code=300087, name='Bergen Trail - Off Road 2 - Chest 2'),
    LocationData(code=300088, name='Bergen Trail - Off Road 2 - Chest 3'),
    LocationData(code=300089, name='Bergen Trail - Off Road 3 - Chest 1'),
    LocationData(code=300090, name='Bergen Trail - Off Road 3 - Chest 2'),
    LocationData(code=300091, name='Bergen Trail - Old Plateau - Gold Chest'),
    LocationData(code=300092, name='Bergen Trail - Rising Path 2 - Chest'),
    LocationData(code=300093, name='Bergen Trail - Rising Path 3 - Chest 1'),
    LocationData(code=300094, name='Bergen Trail - Rising Path 3 - Chest 2'),
    LocationData(code=300095, name='Bergen Trail - Spike Heights - Chest'),
    LocationData(code=300096, name='Bergen Trail - Spike Heights - Bronze Chest'),
    LocationData(code=300097, name='Bergen Trail - Icy Cauldron - Silver Chest'),
    LocationData(code=300098, name='Bergen Trail - Bergen Waterfalls - Chest'),
    LocationData(code=300099, name='Bergen Trail - Rising Path 4 - Chest 1'),
    LocationData(code=300100, name='Bergen Trail - Rising Path 4 - Chest 2'),
    LocationData(code=300101, name='Bergen Trail - Lofty Heights - Bronze Chest'),
    LocationData(code=300102, name='Bergen Trail - Windy Climb - Chest'),
    LocationData(code=300103, name='Bergen Trail - Rising Path 5 - Chest'),
    LocationData(code=300104, name='Temple Mine - Elevator U1 - Chest'),
    LocationData(code=300105, name='Temple Mine - Crossing Funnel - Chest'),
    LocationData(code=300106, name='Temple Mine - Old Shaft 1 - Chest'),
    LocationData(code=300107, name='Temple Mine - Old Shaft 2 - Chest'),
    LocationData(code=300108, name='Temple Mine - Testing Chamber - Chest'),
    LocationData(code=300109, name='Temple Mine - Old Chamber - Chest'),
    LocationData(code=300110, name='Temple Mine - Storage Room 1 - Bronze Chest'),
    LocationData(code=300111, name='Temple Mine - Frozen Chamber 1 - Chest'),
    LocationData(code=300112, name='Temple Mine - Frozen Chamber 2 - Bronze Chest 1'),
    LocationData(code=300113, name='Temple Mine - Frozen Chamber 2 - Bronze Chest 2'),
    LocationData(code=300114, name='Temple Mine - Frozen Shaft 1 - Chest'),
    LocationData(code=300115, name='Temple Mine - Frozen Shaft 2 - Chest'),
    LocationData(code=300116, name='Temple Mine - Frozen Shaft 3 - Chest'),
    LocationData(code=300117, name='Temple Mine - Frozen Shaft 3 - Bronze Chest'),
    LocationData(code=300118, name='Temple Mine - Overrun Chamber - Chest 1'),
    LocationData(code=300119, name='Temple Mine - Overrun Chamber - Chest 2'),
    LocationData(code=300120, name='Temple Mine - Elevator U4 - Chest'),
    LocationData(code=300121, name='Temple Mine - Infested Chamber - Chest'),
    LocationData(code=300122, name='Temple Mine - Forgotten Shaft 1 - Chest'),
    LocationData(code=300123, name='Temple Mine - Forgotten Shaft 2 - Bronze Chest'),
    LocationData(code=300124, name='Temple Mine - Forgotten Shaft 3 - Chest'),
    LocationData(code=300125, name='Temple Mine - Forgotten Shaft 4 - Chest'),
    LocationData(code=300126, name='Temple Mine - Forgotten Shaft 5 - Chest'),
    LocationData(code=300127, name='Temple Mine - Elevator GF - Bronze Chest'),
    LocationData(code=300128, name='Temple Mine - Temple Chamber 2 - Chest'),
    LocationData(code=300129, name='Sapphire Ridge - The Barracks - Bronze Chest'),
    LocationData(code=300130, name='Sapphire Ridge - The Bellow - Gold Chest'),
    LocationData(code=300131, name='Sapphire Ridge - Sapphire Tunnel - Gold Chest'),
    LocationData(code=300132, name='Sapphire Ridge - Eroded Passage - Silver Chest'),
    LocationData(code=300133, name='Sapphire Ridge - Eroded Passage - Chest'),
    LocationData(code=300134, name='Sapphire Ridge - Spider Chasm - Bronze Chest'),
    LocationData(code=300135, name='Sapphire Ridge - Spider Chasm - Gold Chest'),
    LocationData(code=300136, name='Sapphire Ridge - Narrow Passage - Silver Chest'),
    LocationData(code=300137, name='Sapphire Ridge - Narrow Passage - Bronze Chest'),
    LocationData(code=300138, name='Sapphire Ridge - Wheel Passage - Gold Chest'),
    LocationData(code=300139, name='Sapphire Ridge - Wheel Passage - Bronze Chest'),
    LocationData(code=300140, name='Sapphire Ridge - Cave Inn 1F - Chest'),
    LocationData(code=300141, name='Sapphire Ridge - Cave Inn Storage - Gold Chest'),
    LocationData(code=300142, name='Sapphire Ridge - Western Exit - Chest'),
    LocationData(code=300143, name='Sapphire Ridge - Western Exit - Bronze Chest'),
    LocationData(code=300144, name='Sapphire Ridge - North West Path - Silver Chest'),
    LocationData(code=300145, name='Sapphire Ridge - North West Path - Bronze Chest'),
    LocationData(code=300146, name='Sapphire Ridge - River Road - Bronze Chest 1'),
    LocationData(code=300147, name='Sapphire Ridge - River Road - Gold Chest'),
    LocationData(code=300148, name='Sapphire Ridge - River Road - Bronze Chest 2'),
    LocationData(code=300149, name='Sapphire Ridge - The Cave Inn - Bronze Chest'),
    LocationData(code=300150, name='Sapphire Ridge - The Cave Inn - Gold Chest'),
    LocationData(code=300151, name='Sapphire Ridge - Tranquil Bamboo - Bronze Chest'),
    LocationData(code=300152, name='Sapphire Ridge - Tranquil Bamboo - Chest'),
    LocationData(code=300153, name='Sapphire Ridge - Bamboo Thicket - Silver Chest'),
    LocationData(code=300154, name='Sapphire Ridge - Bamboo Thicket - Gold Chest'),
    LocationData(code=300155, name='Sapphire Ridge - North East Path - Silver Chest'),
    LocationData(code=300156, name='Sapphire Ridge - North East Path - Gold Chest'),
    LocationData(code=300157, name='Sapphire Ridge - Flower Lake - Gold Chest 1'),
    LocationData(code=300158, name='Sapphire Ridge - Flower Lake - Gold Chest 2'),
    LocationData(code=300159, name='Sapphire Ridge - Carved Pathway - Gold Chest'),
    LocationData(code=300160, name='Sapphire Ridge - Carved Pathway - Silver Chest'),
    LocationData(code=300161, name='Sapphire Ridge - Carved Pathway - Bronze Chest'),
    LocationData(code=300162, name='Sapphire Ridge - High Ground - Gold Chest'),
    LocationData(code=300163, name='Sapphire Ridge - High Ground - Silver Chest'),
    LocationData(code=300164, name='Sapphire Ridge - Old Dojo - Silver Chest'),
    LocationData(code=300165, name='Sapphire Ridge - Old Dojo - Gold Chest 1'),
    LocationData(code=300166, name='Sapphire Ridge - Old Dojo - Gold Chest 2'),
    LocationData(code=300167, name='Sapphire Ridge - Dream Pond - Gold Chest'),
    LocationData(code=300168, name='Sapphire Ridge - Ascension Temple - Gold Chest'),
    LocationData(code=300169, name='Sapphire Ridge - Ascension Temple - Silver Chest 1'),
    LocationData(code=300170, name='Sapphire Ridge - Ascension Temple - Silver Chest 2'),
    LocationData(code=300171, name='Sapphire Ridge - Baton Pond - Bronze Chest'),
    LocationData(code=300172, name='Maroon Valley - Mystery Cave - Gold Chest'),
    LocationData(code=300173, name='Maroon Valley - Mystery Cave - Silver Chest'),
    LocationData(code=300174, name='Maroon Valley - Cursed Temple - Silver Chest 1'),
    LocationData(code=300175, name='Maroon Valley - Cursed Temple - Silver Chest 2'),
    LocationData(code=300176, name='Maroon Valley - Cursed Temple Treasure Room - Bronze Chest'),
    LocationData(code=300177, name='Maroon Valley - Maroon Cave 1 - Chest'),
    LocationData(code=300178, name='Maroon Valley - River Cliff - Chest 1'),
    LocationData(code=300179, name='Maroon Valley - River Cliff - Chest 2'),
    LocationData(code=300180, name='Maroon Valley - Endless Pit - Chest 1'),
    LocationData(code=300181, name='Maroon Valley - Endless Pit - Chest 2'),
    LocationData(code=300182, name='Maroon Valley - Endless Pit - Chest 3'),
    LocationData(code=300183, name='Maroon Valley - Vivid Path - Chest 1'),
    LocationData(code=300184, name='Maroon Valley - Vivid Path - Chest 2'),
    LocationData(code=300185, name='Maroon Valley - Maroon Oasis - Chest 1'),
    LocationData(code=300186, name='Maroon Valley - Maroon Oasis - Chest 2'),
    LocationData(code=300187, name='Maroon Valley - Bright Path - Bronze Chest'),
    LocationData(code=300188, name='Maroon Valley - Rising Railway - Chest'),
    LocationData(code=300189, name='Maroon Valley - East Entrance - Chest'),
    LocationData(code=300190, name='Maroon Valley - Dusty Path - Bronze Chest'),
    LocationData(code=300191, name='Maroon Valley - Dusty Path - Chest'),
    LocationData(code=300192, name='Maroon Valley - Crossroad - Chest 1'),
    LocationData(code=300193, name='Maroon Valley - Crossroad - Chest 2'),
    LocationData(code=300194, name='Maroon Valley - Long Piece - Chest'),
    LocationData(code=300195, name='Maroon Valley - Barren Arcs - Chest'),
    LocationData(code=300196, name='Maroon Valley - Barren Arcs - Bronze Chest'),
    LocationData(code=300197, name='Maroon Valley - Barren Land - Chest'),
    LocationData(code=300198, name='Maroon Valley - Overpass - Chest 1'),
    LocationData(code=300199, name='Maroon Valley - Overpass - Chest 2'),
    LocationData(code=300200, name='Maroon Valley - Paw Cliffs - Chest'),
    LocationData(code=300201, name='Maroon Valley - Paw Cliffs - Silver Chest'),
    LocationData(code=300202, name='Maroon Valley - Torn Road - Chest 1'),
    LocationData(code=300203, name='Maroon Valley - Torn Road - Chest 2'),
    LocationData(code=300204, name='Maroon Valley - West Entrance - Chest'),
    LocationData(code=300205, name='Maroon Valley - Fractured Path - Silver Chest'),
    LocationData(code=300206, name='Maroon Valley - Fractured Path - Chest'),
    LocationData(code=300207, name="Faj'ro Temple - Right Chamber 1 (1F) - Chest"),
    LocationData(code=300208, name="Faj'ro Temple - Bottom Chamber - Chest"),
    LocationData(code=300209, name="Faj'ro Temple - Large Fire Chamber - Bronze Chest"),
    LocationData(code=300210, name="Faj'ro Temple - Large Fire Chamber - Silver Chest"),
    LocationData(code=300211, name="Faj'ro Temple - Test of Wisdom - Chest"),
    LocationData(code=300212, name="Faj'ro Temple - West Pathway - Chest"),
    LocationData(code=300213, name="Faj'ro Temple - Test of Surprise - Chest"),
    LocationData(code=300214, name="Faj'ro Temple - West Chamber 1 - Chest"),
    LocationData(code=300215, name="Faj'ro Temple - East Chamber 1 - Chest"),
    LocationData(code=300216, name="Faj'ro Temple - East Pathway - Silver Chest"),
    LocationData(code=300217, name="Faj'ro Temple - Test of Memory - Chest"),
    LocationData(code=300218, name="Faj'ro Temple - Chamber of Prosperity - Chest"),
    LocationData(code=300219, name="Faj'ro Temple - Left Chamber 1 - Chest"),
    LocationData(code=300220, name="Faj'ro Temple - Fire and Sand 2 - Chest"),
    LocationData(code=300221, name="Faj'ro Temple - Balance Room 2 - Chest 1"),
    LocationData(code=300222, name="Faj'ro Temple - Balance Room 2 - Chest 2"),
    LocationData(code=300223, name="Faj'ro Temple - Right Chamber 1 (GF) - Chest"),
    LocationData(code=300224, name="Faj'ro Temple - Right Chamber 2 - Chest"),
    LocationData(code=300225, name="Faj'ro Temple - Test of Memory 1 - Chest"),
    LocationData(code=300226, name="Faj'ro Temple - Test of Memory 2 - Chest"),
    LocationData(code=300227, name="Ba'kii Kum - Solar Farm - Chest 1"),
    LocationData(code=300228, name="Ba'kii Kum - Solar Farm - Chest 2"),
    LocationData(code=300229, name="Ba'kii Kum - Market - Chest"),
    LocationData(code=300230, name="Ba'kii Kum - Market - Bronze Chest"),
    LocationData(code=300231, name="Ba'kii Kum - Bazaar House - Silver Chest"),
    LocationData(code=300232, name="Gaia's Garden - Dripping Cave - Silver Chest"),
    LocationData(code=300233, name="Gaia's Garden - Tranquility Pond - Gold Chest"),
    LocationData(code=300234, name="Gaia's Garden - Infested Cavern - Bronze Chest"),
    LocationData(code=300235, name="Gaia's Garden - Infested Cavern - Silver Chest"),
    LocationData(code=300236, name="Gaia's Garden - V'rda Vil West - Gold Chest"),
    LocationData(code=300237, name="Gaia's Garden - V'rda Vil West - Silver Chest"),
    LocationData(code=300238, name="Gaia's Garden - V'rda Vil West - Bronze Chest"),
    LocationData(code=300239, name="Gaia's Garden - V'rda Vil East - Bronze Chest"),
    LocationData(code=300240, name="Gaia's Garden - V'rda Vil East - Silver Chest"),
    LocationData(code=300241, name="Gaia's Garden - V'rda Vil North - Gold Chest"),
    LocationData(code=300242, name="Gaia's Garden - V'rda Vil North - Silver Chest"),
    LocationData(code=300243, name="Gaia's Garden - Chief's Den - Silver Chest"),
    LocationData(code=300244, name="Gaia's Garden - Chief's Den - Bronze Chest"),
    LocationData(code=300245, name="Gaia's Garden - Chief's Den - Gold Chest"),
    LocationData(code=300246, name="Gaia's Garden - Grand Krys'kajo Entrance - Bronze Chest"),
    LocationData(code=300247, name="Gaia's Garden - So'najiz Temple Entrance - Silver Chest"),
    LocationData(code=300248, name="Gaia's Garden - Covert Path - Chest 1"),
    LocationData(code=300249, name="Gaia's Garden - Covert Path - Chest 2"),
    LocationData(code=300250, name="Gaia's Garden - Royal Grove - Silver Chest"),
    LocationData(code=300251, name="Gaia's Garden - Royal Grove - Chest 1"),
    LocationData(code=300252, name="Gaia's Garden - Royal Grove - Chest 2"),
    LocationData(code=300253, name="Gaia's Garden - Royal Grove - Chest 3"),
    LocationData(code=300254, name="Gaia's Garden - Calm Backyard - Chest 1"),
    LocationData(code=300255, name="Gaia's Garden - Calm Backyard - Chest 2"),
    LocationData(code=300256, name="Gaia's Garden - Lost Shrine Interior 1F - Chest"),
    LocationData(code=300257, name="Gaia's Garden - Lost Shrine Interior B1 - Gold Chest"),
    LocationData(code=300258, name="Gaia's Garden - Lost Shrine Interior B2 - Silver Chest"),
    LocationData(code=300259, name="Gaia's Garden - Lost Lookout - Chest 1"),
    LocationData(code=300260, name="Gaia's Garden - Lost Lookout - Chest 2"),
    LocationData(code=300261, name="Gaia's Garden - Lost Lookout - Chest 3"),
    LocationData(code=300262, name="Gaia's Garden - Seared Lake - Chest 1"),
    LocationData(code=300263, name="Gaia's Garden - Seared Lake - Chest 2"),
    LocationData(code=300264, name="Gaia's Garden - Infested Marshes South - Chest 1"),
    LocationData(code=300265, name="Gaia's Garden - Infested Marshes South - Chest 2"),
    LocationData(code=300266, name="Gaia's Garden - Infested Marshes South - Chest 3"),
    LocationData(code=300267, name="Gaia's Garden - Infested Marshes South - Chest 4"),
    LocationData(code=300268, name="Gaia's Garden - Infested Marshes North - Chest 1"),
    LocationData(code=300269, name="Gaia's Garden - Infested Marshes North - Chest 2"),
    LocationData(code=300270, name="Gaia's Garden - Infested Marshes North - Silver Chest 1"),
    LocationData(code=300271, name="Gaia's Garden - Infested Marshes North - Silver Chest 2"),
    LocationData(code=300272, name="Gaia's Garden - Overgrown Path - Bronze Chest 1"),
    LocationData(code=300273, name="Gaia's Garden - Overgrown Path - Bronze Chest 2"),
    LocationData(code=300274, name="Gaia's Garden - Drizzle Bosk - Gold Chest"),
    LocationData(code=300275, name="Gaia's Garden - Drizzle Bosk - Chest 1"),
    LocationData(code=300276, name="Gaia's Garden - Drizzle Bosk - Chest 2"),
    LocationData(code=300277, name="Gaia's Garden - Wet Passage - Bronze Chest"),
    LocationData(code=300278, name="Gaia's Garden - Wet Passage - Chest"),
    LocationData(code=300279, name="Gaia's Garden - River's Bed - Silver Chest"),
    LocationData(code=300280, name="Gaia's Garden - River's Bed - Chest"),
    LocationData(code=300281, name="Gaia's Garden - Jungle Entrance - Chest 1"),
    LocationData(code=300282, name="Gaia's Garden - Jungle Entrance - Chest 2"),
    LocationData(code=300283, name="Gaia's Garden - Crossroad - Gold Chest"),
    LocationData(code=300284, name="Gaia's Garden - Crossroad - Chest"),
    LocationData(code=300285, name="Gaia's Garden - Tying Greens - Chest 1"),
    LocationData(code=300286, name="Gaia's Garden - Tying Greens - Chest 2"),
    LocationData(code=300287, name="Gaia's Garden - Peridot Approach - Silver Chest"),
    LocationData(code=300288, name="Gaia's Garden - Peridot Approach - Chest"),
    LocationData(code=300289, name="Gaia's Garden - Splitting Stumps - Chest 1"),
    LocationData(code=300290, name="Gaia's Garden - Splitting Stumps - Chest 2"),
    LocationData(code=300291, name="Gaia's Garden - Clinging River - Silver Chest"),
    LocationData(code=300292, name="Gaia's Garden - Clinging River - Gold Chest"),
    LocationData(code=300293, name="Gaia's Garden - Ringing River - Bronze Chest"),
    LocationData(code=300294, name="Gaia's Garden - Ringing River - Chest"),
    LocationData(code=300295, name="Gaia's Garden - Old Timber - Chest"),
    LocationData(code=300296, name='Basin Keep - Centrum - Gold Chest'),
    LocationData(code=300297, name='Basin Keep - Pond Slums - Silver Chest 1'),
    LocationData(code=300298, name='Basin Keep - Pond Slums - Silver Chest 2'),
    LocationData(code=300299, name='Basin Keep - Pond Slums - Gold Chest'),
    LocationData(code=300300, name="Gaia's Garden - Basin Keep Entrance - Chest"),
    LocationData(code=300301, name='Basin Keep - Basin Police Force HQ - Gold Chest'),
    LocationData(code=300302, name='Basin Keep - Seeker Hub 1st Floor - Silver Chest'),
    LocationData(code=300303, name='Rhombus Dungeon - Ability Room 1 - Chest 1'),
    LocationData(code=300304, name='Rhombus Dungeon - Ability Room 1 - Chest 2'),
    LocationData(code=300305, name='Rhombus Square - Arena Plaza - Bronze Chest'),
    LocationData(code=300306, name='Rhombus Square - Arena Plaza - Silver Chest'),
    LocationData(code=300307, name='Rhombus Square - Garden Boulevard - Bronze Chest'),
    LocationData(code=300308, name='Rhombus Square - Garden Boulevard - Silver Chest'),
    LocationData(code=300309, name='Rhombus Square - South Arch - Gold Chest'),
    LocationData(code=300310, name='Rhombus Square - Lloyd Passage - Silver Chest'),
    LocationData(code=300311, name='Rhombus Square - Residential District West - Gold Chest'),
    LocationData(code=300312, name='Rhombus Square - Residential District West - Chest'),
    LocationData(code=300313, name='Rookie Harbor - Marketplace - Chest'),
    LocationData(code=300314, name='Rookie Harbor - Falling Exit - Chest'),
    LocationData(code=300315, name='Rookie Harbor - Weapon & Backer Shop - Silver Chest'),
    LocationData(code=300316, name='Rookie Harbor - Dusty Storage - Silver Chest'),
    LocationData(code=300317, name='Rookie Harbor - South Harbor - Gold Chest'),
    LocationData(code=300318, name='Rookie Harbor - Beginners Arc - Chest 1'),
    LocationData(code=300319, name='Rookie Harbor - Beginners Arc - Chest 2'),
    LocationData(code=300320, name="Zir'vitar Temple - Moving Transmit - Chest 1"),
    LocationData(code=300321, name="Zir'vitar Temple - Moving Transmit - Chest 2"),
    LocationData(code=300322, name="Zir'vitar Temple - Haunted Waves - Bronze Chest"),
    LocationData(code=300323, name="Zir'vitar Temple - Hoodwink - Chest"),
    LocationData(code=300324, name="Zir'vitar Temple - Spinning Transmit - Bronze Chest"),
    LocationData(code=300325, name="Grand Krys'kajo - East Branch - Gold Chest"),
    LocationData(code=300326, name="Grand Krys'kajo - East Branch - Chest 1"),
    LocationData(code=300327, name="Grand Krys'kajo - East Branch - Chest 2"),
    LocationData(code=300328, name="Grand Krys'kajo - West Branch - Chest 1"),
    LocationData(code=300329, name="Grand Krys'kajo - West Branch - Chest 2"),
    LocationData(code=300330, name="Grand Krys'kajo - Falling Leaves - Chest"),
    LocationData(code=300331, name="Grand Krys'kajo - Branch Conveyance - Chest"),
    LocationData(code=300332, name="Grand Krys'kajo - Branch Transmit - Chest 1"),
    LocationData(code=300333, name="Grand Krys'kajo - Branch Transmit - Chest 2"),
    LocationData(code=300334, name="So'najiz Temple - Principle of Conveyance - Chest"),
    LocationData(code=300335, name="So'najiz Temple - Trial of Persistence - Chest 1"),
    LocationData(code=300336, name="So'najiz Temple - Trial of Persistence - Chest 2"),
    LocationData(code=300337, name="So'najiz Temple - Trial of Persistence - Chest 3"),
    LocationData(code=300338, name="So'najiz Temple - Trial of Persistence - Silver Chest"),
    LocationData(code=300339, name="So'najiz Temple - Trial of Persistence - Gold Chest"),
    LocationData(code=300340, name="So'najiz Temple - Moving Attraction - Chest"),
    LocationData(code=300341, name="So'najiz Temple - Slowing Attraction - Chest"),
    LocationData(code=300342, name="So'najiz Temple - Standing Attraction - Chest"),
    LocationData(code=300343, name="So'najiz Temple - Attracting Conveyance - Chest"),
    LocationData(code=300344, name="So'najiz Temple - Fast Conveyance - Chest"),
    LocationData(code=300345, name="So'najiz Temple - Flaming Conveyance - Chest"),
    LocationData(code=300346, name='Talatu Introductions'),
    LocationData(code=300347, name='Talatu Bergen 25%'),
    LocationData(code=300348, name="Talatu Ba'kii 50%"),
    LocationData(code=300349, name='Talatu Basin 75%'),
    LocationData(code=300350, name='Schneider Guild Pass'),
    LocationData(code=300351, name='Bergen Mine Guard'),
    LocationData(code=300352, name='Temple Mine Shade Statue'),
    LocationData(code=300353, name='Old Dojo Shade Statue'),
    LocationData(code=300354, name='Vagabond Dojo Key'),
    LocationData(code=300355, name="Faj'ro Shade Statue"),
    LocationData(code=300356, name="Ba'kii Kum Cursed Man"),
    LocationData(code=300357, name="Ba'kii Eldress"),
    LocationData(code=300358, name="Ba'kii Shade Statue"),
    LocationData(code=300359, name="Zir'vitar Shade Statue"),
    LocationData(code=300360, name="Krys'kajo Shade Statue"),
    LocationData(code=300361, name="So'najiz Shade Statue"),
    LocationData(code=300362, name='Rookie Harbor Shade'),
    LocationData(code=300363, name='Rookie Harbor Disc'),
    LocationData(code=300364, name='Rookie Harbor Post Mine'),
    LocationData(code=300365, name="Rookie Harbor Post Faj'ro"),
    LocationData(code=300366, name="Rookie Harbor Post Krys'kajo"),
    LocationData(code=300367, name="Rookie Harbor Post So'najiz"),
    LocationData(code=300368, name="Rookie Harbor Post Zir'vitar"),
    LocationData(code=300369, name='Heat Pedestal'),
    LocationData(code=300370, name='Cold Pedestal'),
    LocationData(code=300371, name='Shock Pedestal'),
    LocationData(code=300372, name='Wave Pedestal'),
    LocationData(code=300373, name='Chase the Hologram Frobbit'),
    LocationData(code=300472, name='Mushroom Kingdom'),
    LocationData(code=300376, name='First Steps'),
    LocationData(code=300378, name='A Few More Steps'),
    LocationData(code=300379, name="Autumn's Rise Trailblazing"),
    LocationData(code=300380, name="Autumn's Rise Collect"),
    LocationData(code=300381, name="Autumn's Rise Defeat"),
    LocationData(code=300382, name="Autumn's Rise Landmarks"),
    LocationData(code=300383, name="Autumn's Rise Data Probe"),
    LocationData(code=300386, name='Round and Round'),
    LocationData(code=300387, name='Crocus Pocus'),
    LocationData(code=300388, name='The Observatory'),
    LocationData(code=300389, name='Bergen Trailblazing'),
    LocationData(code=300390, name='Bergen Trailblazing Collect'),
    LocationData(code=300391, name='Bergen Trailblazing Defeat'),
    LocationData(code=300392, name='Bergen Trailblazing Landmarks'),
    LocationData(code=300393, name='Bergen Trailblazing Data Probe'),
    LocationData(code=300395, name="You've Got Mail"),
    LocationData(code=300396, name='The Legendary Bunny'),
    LocationData(code=300399, name='Round and Round 2'),
    LocationData(code=300400, name='Digging Up the Past'),
    LocationData(code=300402, name='Filthy Frobbits'),
    LocationData(code=300404, name='Explosive Debugging'),
    LocationData(code=300406, name='Preemptive Mining'),
    LocationData(code=300408, name='Kidding Around'),
    LocationData(code=300410, name='The Goatfather'),
    LocationData(code=300412, name='Fancy Tophat'),
    LocationData(code=300415, name='Heating the Hermit'),
    LocationData(code=300417, name='Trial of Aspiration'),
    LocationData(code=300420, name='Trial of Progression'),
    LocationData(code=300421, name='Challenge of Aspiration'),
    LocationData(code=300422, name='Aspiration Timed Challenge'),
    LocationData(code=300423, name='Aspiration No Shield Challenge'),
    LocationData(code=300424, name='Challenge of Progression'),
    LocationData(code=300425, name='Progression Timed Challenge'),
    LocationData(code=300426, name='Progression Frosty Challenge'),
    LocationData(code=300427, name='Building a Base'),
    LocationData(code=300428, name='Pushing Bases'),
    LocationData(code=300429, name='A Promise is a Promise 2'),
    LocationData(code=300430, name='Henry Trailblazing'),
    LocationData(code=300431, name='Last Minute Help Needed'),
    LocationData(code=300432, name='An Unfortunate Series of Features'),
    LocationData(code=300433, name='Maroon Valley Trailblazing'),
    LocationData(code=300434, name='Maroon Valley Collect'),
    LocationData(code=300435, name='Maroon Valley Defeat'),
    LocationData(code=300436, name='Maroon Valley Landmarks'),
    LocationData(code=300437, name='Maroon Valley Data Probe'),
    LocationData(code=300438, name='Maroon Tree Defender'),
    LocationData(code=300440, name='Blasting Shells'),
    LocationData(code=300441, name='Hot Trail'),
    LocationData(code=300443, name='Waves of Sand'),
    LocationData(code=300445, name='Shady Thief'),
    LocationData(code=300447, name='Just Deserts'),
    LocationData(code=300449, name='Crate Hate'),
    LocationData(code=300450, name='Steamy Booze'),
    LocationData(code=300451, name='Steamy Challenge'),
    LocationData(code=300452, name='A Promise is a Promise 3'),
    LocationData(code=300454, name='Turret Defense'),
    LocationData(code=300456, name='An Original Idea'),
    LocationData(code=300458, name='Hostage Situation'),
    LocationData(code=300460, name='High Crating'),
    LocationData(code=300463, name='Tropical Chill'),
    LocationData(code=300464, name='Melting this Cold Fiend'),
    LocationData(code=300467, name='Lakeside Escort'),
    LocationData(code=300470, name='Rooting for Power'),
    LocationData(code=300471, name='Sprouting Business'),
    LocationData(code=300473, name='Pumpkin Land Superfun'),
    LocationData(code=300474, name='A Promise is a Promise 4'),
    LocationData(code=300475, name="Gaia's Garden Trailblazing"),
    LocationData(code=300476, name="Gaia's Garden Collect"),
    LocationData(code=300477, name="Gaia's Garden Defeat"),
    LocationData(code=300478, name="Gaia's Garden Landmarks"),
    LocationData(code=300479, name="Gaia's Garden Data Probe"),
    LocationData(code=300480, name='Turret Defense Challenge 1'),
    LocationData(code=300481, name='Turret Defense Challenge 2'),
    LocationData(code=300482, name='A Promise is a Promise 5'),
    LocationData(code=300483, name='Railing Rider'),
    LocationData(code=300484, name='All Hail the Ice Cream'),
    LocationData(code=300485, name='Training with the Master'),
    LocationData(code=300486, name='Training: VRP'),
    LocationData(code=300487, name='Training: VPI'),
    LocationData(code=300488, name='Faction Introduction'),
    LocationData(code=300489, name='Digging for Data'),
    LocationData(code=300491, name="It Can Dig But It Can't Hide"),
    LocationData(code=300493, name='Points of Power'),
    LocationData(code=300495, name='Petty Crime Hunter'),
    LocationData(code=300497, name='Smuggle Trouble'),
    LocationData(code=300499, name='Wet Work'),
    LocationData(code=300501, name='Small Time Delivery'),
    LocationData(code=300504, name='Bull Grab'),
    LocationData(code=300506, name='New Metal'),
    LocationData(code=300508, name='Sickly Trees'),
    LocationData(code=300511, name='Intensive Tree Care'),
    LocationData(code=300514, name='Bull on Fire'),
    LocationData(code=300515, name='A Promise is a Promise'),
    LocationData(code=300517, name="Wood 'n' Steaks"),
    LocationData(code=300518, name='Meating Expectations'),
    LocationData(code=300519, name='Raising the Steaks'),
]

locations_dict = { location.name: location for location in locations_data }

events_data = [
    LocationData(code=None, name='Chase the Hologram Frobbit (Event)'),
    LocationData(code=None, name='Mushroom Kingdom (Event)'),
    LocationData(code=None, name='First Steps (Event)'),
    LocationData(code=None, name='A Few More Steps (Event)'),
    LocationData(code=None, name="Autumn's Rise Trailblazing (Event)"),
    LocationData(code=None, name="Autumn's Rise Collect (Event)"),
    LocationData(code=None, name="Autumn's Rise Defeat (Event)"),
    LocationData(code=None, name="Autumn's Rise Landmarks (Event)"),
    LocationData(code=None, name="Autumn's Rise Data Probe (Event)"),
    LocationData(code=None, name='Round and Round (Event)'),
    LocationData(code=None, name='Crocus Pocus (Event)'),
    LocationData(code=None, name='The Observatory (Event)'),
    LocationData(code=None, name='Bergen Trailblazing (Event)'),
    LocationData(code=None, name='Bergen Trailblazing Collect (Event)'),
    LocationData(code=None, name='Bergen Trailblazing Defeat (Event)'),
    LocationData(code=None, name='Bergen Trailblazing Landmarks (Event)'),
    LocationData(code=None, name='Bergen Trailblazing Data Probe (Event)'),
    LocationData(code=None, name="You've Got Mail (Event)"),
    LocationData(code=None, name='The Legendary Bunny (Event)'),
    LocationData(code=None, name='Round and Round 2 (Event)'),
    LocationData(code=None, name='Digging Up the Past (Event)'),
    LocationData(code=None, name='Filthy Frobbits (Event)'),
    LocationData(code=None, name='Explosive Debugging (Event)'),
    LocationData(code=None, name='Preemptive Mining (Event)'),
    LocationData(code=None, name='Kidding Around (Event)'),
    LocationData(code=None, name='The Goatfather (Event)'),
    LocationData(code=None, name='Fancy Tophat (Event)'),
    LocationData(code=None, name='Heating the Hermit (Event)'),
    LocationData(code=None, name='Trial of Aspiration (Event)'),
    LocationData(code=None, name='Trial of Progression (Event)'),
    LocationData(code=None, name='Challenge of Aspiration (Event)'),
    LocationData(code=None, name='Aspiration Timed Challenge (Event)'),
    LocationData(code=None, name='Aspiration No Shield Challenge (Event)'),
    LocationData(code=None, name='Challenge of Progression (Event)'),
    LocationData(code=None, name='Progression Timed Challenge (Event)'),
    LocationData(code=None, name='Progression Frosty Challenge (Event)'),
    LocationData(code=None, name='Building a Base (Event)'),
    LocationData(code=None, name='Pushing Bases (Event)'),
    LocationData(code=None, name='A Promise is a Promise 2 (Event)'),
    LocationData(code=None, name='Henry Trailblazing (Event)'),
    LocationData(code=None, name='Last Minute Help Needed (Event)'),
    LocationData(code=None, name='An Unfortunate Series of Features (Event)'),
    LocationData(code=None, name='Maroon Valley Trailblazing (Event)'),
    LocationData(code=None, name='Maroon Valley Collect (Event)'),
    LocationData(code=None, name='Maroon Valley Defeat (Event)'),
    LocationData(code=None, name='Maroon Valley Landmarks (Event)'),
    LocationData(code=None, name='Maroon Valley Data Probe (Event)'),
    LocationData(code=None, name='Maroon Tree Defender (Event)'),
    LocationData(code=None, name='Blasting Shells (Event)'),
    LocationData(code=None, name='Hot Trail (Event)'),
    LocationData(code=None, name='Waves of Sand (Event)'),
    LocationData(code=None, name='Shady Thief (Event)'),
    LocationData(code=None, name='Just Deserts (Event)'),
    LocationData(code=None, name='Crate Hate (Event)'),
    LocationData(code=None, name='Steamy Booze (Event)'),
    LocationData(code=None, name='Steamy Challenge (Event)'),
    LocationData(code=None, name='A Promise is a Promise 3 (Event)'),
    LocationData(code=None, name='Turret Defense (Event)'),
    LocationData(code=None, name='An Original Idea (Event)'),
    LocationData(code=None, name='Hostage Situation (Event)'),
    LocationData(code=None, name='High Crating (Event)'),
    LocationData(code=None, name='Tropical Chill (Event)'),
    LocationData(code=None, name='Melting this Cold Fiend (Event)'),
    LocationData(code=None, name='Lakeside Escort (Event)'),
    LocationData(code=None, name='Rooting for Power (Event)'),
    LocationData(code=None, name='Sprouting Business (Event)'),
    LocationData(code=None, name='Pumpkin Land Superfun (Event)'),
    LocationData(code=None, name='A Promise is a Promise 4 (Event)'),
    LocationData(code=None, name="Gaia's Garden Trailblazing (Event)"),
    LocationData(code=None, name="Gaia's Garden Collect (Event)"),
    LocationData(code=None, name="Gaia's Garden Defeat (Event)"),
    LocationData(code=None, name="Gaia's Garden Landmarks (Event)"),
    LocationData(code=None, name="Gaia's Garden Data Probe (Event)"),
    LocationData(code=None, name='Turret Defense Challenge 1 (Event)'),
    LocationData(code=None, name='Turret Defense Challenge 2 (Event)'),
    LocationData(code=None, name='A Promise is a Promise 5 (Event)'),
    LocationData(code=None, name='Railing Rider (Event)'),
    LocationData(code=None, name='All Hail the Ice Cream (Event)'),
    LocationData(code=None, name='Training with the Master (Event)'),
    LocationData(code=None, name='Training: VRP (Event)'),
    LocationData(code=None, name='Training: VPI (Event)'),
    LocationData(code=None, name='Faction Introduction (Event)'),
    LocationData(code=None, name='Digging for Data (Event)'),
    LocationData(code=None, name="It Can Dig But It Can't Hide (Event)"),
    LocationData(code=None, name='Points of Power (Event)'),
    LocationData(code=None, name='Petty Crime Hunter (Event)'),
    LocationData(code=None, name='Smuggle Trouble (Event)'),
    LocationData(code=None, name='Wet Work (Event)'),
    LocationData(code=None, name='Small Time Delivery (Event)'),
    LocationData(code=None, name='Bull Grab (Event)'),
    LocationData(code=None, name='New Metal (Event)'),
    LocationData(code=None, name='Sickly Trees (Event)'),
    LocationData(code=None, name='Intensive Tree Care (Event)'),
    LocationData(code=None, name='Bull on Fire (Event)'),
    LocationData(code=None, name='A Promise is a Promise (Event)'),
    LocationData(code=None, name="Wood 'n' Steaks (Event)"),
    LocationData(code=None, name='Meating Expectations (Event)'),
    LocationData(code=None, name='Raising the Steaks (Event)'),
]